# Generated by Django 2.1.7 on 2019-07-11 18:23
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0002_auto_20180814_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="has_car",
            field=models.BooleanField(
                default=True,
                help_text="Leave checked if you are offering a ride, uncheck if you need a ride",
            ),
        ),
    ]
