# Generated by Django 2.1.7 on 2019-07-11 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rideshare", "0003_ride_has_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="location",
            new_name="from_location",
        ),
    ]
