# Generated by Django 3.0.3 on 2020-02-19 19:08
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The url slug for this wish. Leave blank to autogenerate one.",
            ),
        ),
    ]
