# Generated by Django 3.0.3 on 2020-05-09 12:14
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0002_auto_20200219_2008"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wish",
            options={"verbose_name_plural": "wishes"},
        ),
        migrations.AlterField(
            model_name="wish",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The url slug for this wish. Leave blank to autogenerate one.",
                unique=True,
            ),
        ),
    ]
