# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='camp',
            field=models.ForeignKey(help_text='Which camp does this day belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='camps.Camp', verbose_name='Camp'),
        ),
    ]
