# Generated by Django 1.9.1 on 2016-01-17 17:18
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="camp",
            field=models.ForeignKey(
                help_text="Which camp does this day belong to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="camps.Camp",
                verbose_name="Camp",
            ),
        ),
    ]
