# Generated by Django 1.9.2 on 2016-04-22 20:19


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("camps", "0002_auto_20160117_1718")]

    operations = [
        migrations.RemoveField(model_name="signup", name="camp"),
        migrations.RemoveField(model_name="signup", name="user"),
        migrations.DeleteModel(name="Signup"),
    ]
