# Generated by Django 1.9.5 on 2016-05-06 20:16


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0003_auto_20160422_2019")]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="ticket_sale_open",
            field=models.BooleanField(
                default=False,
                help_text="Whether tickets are for sale or not.",
                verbose_name="Ticket sale open?",
            ),
        ),
    ]
