# Generated by Django 1.9.6 on 2016-08-04 17:05


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("camps", "0005_auto_20160510_2011")]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "ordering": ["date"],
                "verbose_name": "Day",
                "verbose_name_plural": "Days",
            },
        ),
    ]
