# Generated by Django 1.10.4 on 2016-12-12 18:03
from __future__ import annotations

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("camps", "0006_auto_20160804_1705"),
    ]

    operations = [
        migrations.RemoveField(model_name="day", name="camp"),
        migrations.RemoveField(model_name="camp", name="shop_open"),
        migrations.RemoveField(model_name="expense", name="amount"),
        migrations.RemoveField(model_name="expense", name="camp"),
        migrations.RemoveField(model_name="expense", name="covered_by"),
        migrations.RemoveField(model_name="expense", name="currency"),
        migrations.AddField(
            model_name="camp",
            name="slug",
            field=models.SlugField(
                default="",
                help_text=b"The url slug to use for this camp",
                verbose_name=b"Url Slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="dkk_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text=b"The DKK amount of the expense.",
                max_digits=7,
                verbose_name=b"DKK Amount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_time",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 12, 12, 18, 3, 10, 378604, tzinfo=datetime.UTC),
                help_text=b"The date and time this expense was paid.",
                verbose_name=b"Expense date/time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.ImageField(
                default="",
                help_text=b"Upload a scan or image of the receipt",
                upload_to=b"",
                verbose_name=b"Image of receipt",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="refund_paid",
            field=models.BooleanField(
                default=False,
                help_text=b"Has this expense been refunded to the user?",
                verbose_name=b"Refund paid?",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="refund_user",
            field=models.ForeignKey(
                blank=True,
                help_text=b"Which user, if any, covered this expense and should be refunded.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name=b"Refund user",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="end",
            field=models.DateTimeField(
                help_text=b"When the camp ends.",
                verbose_name=b"End date",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="name",
            field=models.CharField(
                help_text=b"Name of the camp, ie. Bornhack 2016.",
                max_length=255,
                verbose_name=b"Name",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="start",
            field=models.DateTimeField(
                help_text=b"When the camp starts.",
                verbose_name=b"Start date",
            ),
        ),
    ]
