# Generated by Django 1.10.4 on 2016-12-20 17:14
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0009_auto_20161220_1645")]

    operations = [
        migrations.RemoveField(model_name="camp", name="name"),
        migrations.AddField(
            model_name="camp",
            name="tagline",
            field=models.CharField(
                default="",
                help_text=b'Tagline of the camp, ie. "Initial Commit"',
                max_length=255,
                verbose_name=b"Tagline",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camp",
            name="title",
            field=models.CharField(
                default="",
                help_text=b"Title of the camp, ie. Bornhack 2016.",
                max_length=255,
                verbose_name=b"Title",
            ),
            preserve_default=False,
        ),
    ]
