# Generated by Django 1.10.5 on 2017-03-07 20:04
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0019_auto_20170131_1849")]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="read_only",
            field=models.BooleanField(
                default=False,
                help_text="Whether the camp is read only (i.e. in the past)",
            ),
        ),
    ]
