# Generated by Django 1.10.5 on 2017-07-11 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("camps", "0020_camp_read_only")]

    operations = [
        migrations.AlterModelOptions(
            name="camp",
            options={
                "ordering": ["-title"],
                "verbose_name": "Camp",
                "verbose_name_plural": "Camps",
            },
        ),
    ]
