# Generated by Django 1.10.5 on 2018-03-18 11:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0024_populate_camp_shortslugs")]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="shortslug",
            field=models.SlugField(
                help_text="Abbreviated version of the slug. Used in IRC channel names and other places with restricted name length.",
                verbose_name="Short Slug",
            ),
        ),
    ]
