# Generated by Django 2.0.4 on 2018-05-06 14:33
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0025_auto_20180318_1250")]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="call_for_participation_open",
            field=models.BooleanField(
                default=False,
                help_text="Check if the Call for Participation is open for this camp",
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="call_for_sponsors_open",
            field=models.BooleanField(
                default=False,
                help_text="Check if the Call for Sponsors is open for this camp",
            ),
        ),
    ]
