# Generated by Django 2.0.4 on 2018-05-25 08:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0026_auto_20180506_1633")]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="call_for_participation",
            field=models.TextField(
                blank=True,
                help_text="The CFP markdown for this Camp",
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="call_for_sponsors",
            field=models.TextField(
                blank=True,
                help_text="The CFS markdown for this Camp",
            ),
        ),
    ]
