# Generated by Django 2.0.4 on 2018-05-25 08:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0027_auto_20180525_1019")]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="call_for_participation",
            field=models.TextField(
                blank=True,
                default="The Call For Participation for this Camp has not been written yet",
                help_text="The CFP markdown for this Camp",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="call_for_sponsors",
            field=models.TextField(
                blank=True,
                default="The Call For Sponsors for this Camp has not been written yet",
                help_text="The CFS markdown for this Camp",
            ),
        ),
    ]
