# Generated by Django 2.0.4 on 2018-08-18 15:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0029_auto_20180815_2018")]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="light_text",
            field=models.BooleanField(
                default=True,
                help_text="Check if this camps colour requires white text, uncheck if black text is better",
            ),
        ),
    ]
