# Generated by Django 2.2.2 on 2019-06-24 13:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0032_auto_20180917_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="show_schedule",
            field=models.BooleanField(
                default=True,
                help_text="Check if the schedule should be shown.",
            ),
        ),
    ]
