# Generated by Django 3.0.3 on 2020-02-19 19:08
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0033_camp_show_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("backoffice_permission", "BackOffice access"),
                    ("badgeteam_permission", "Badge Team permissions set"),
                    ("barteam_permission", "Bar Team permissions set"),
                    ("certteam_permission", "CERT Team permissions set"),
                    (
                        "constructionteam_permission",
                        "Construction Team permissions set",
                    ),
                    ("contentteam_permission", "Content Team permissions set"),
                    ("economyteam_permission", "Economy Team permissions set"),
                    ("foodareateam_permission", "Foodarea Team permissions set"),
                    ("infoteam_permission", "Info Team permissions set"),
                    ("lightteam_permission", "Light Team permissions set"),
                    ("logisticsteam_permission", "Logistics Team permissions set"),
                    ("metricsteam_permission", "Metrics Team permissions set"),
                    ("nocteam_permission", "NOC Team permissions set"),
                    ("orgateam_permission", "Orga Team permissions set"),
                    ("pocteam_permission", "POC Team permissions set"),
                    ("prteam_permission", "PR Team permissions set"),
                    ("phototeam_permission", "Photo Team permissions set"),
                    ("powerteam_permission", "Power Team permissions set"),
                    ("rocteam_permission", "ROC Team permissions set"),
                    ("sanitationteam_permission", "Sanitation Team permissions set"),
                    ("shuttleteam_permission", "Shuttle Team permissions set"),
                    ("sponsorsteam_permission", "Sponsors Team permissions set"),
                    ("sysadminteam_permission", "Sysadmin Team permissions set"),
                    ("videoteam_permission", "Video Team permissions set"),
                    ("websiteteam_permission", "Website Team permissions set"),
                    ("wellnessteam_permission", "Wellness Team permissions set"),
                    ("expense_create_permission", "Expense Create permission"),
                    ("revenue_create_permission", "Revenue Create permission"),
                ),
            },
        ),
    ]
