# Generated by Django 4.2.16 on 2024-09-29 11:39
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0037_alter_permission_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("expense_create_permission", "Expense Create permission"),
                    ("revenue_create_permission", "Revenue Create permission"),
                ),
            },
        ),
    ]
