# Generated by Django 4.2.21 on 2025-05-28 22:50
from __future__ import annotations

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0038_alter_permission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="kickoff",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True,
                help_text="The camp kickoff period.",
                null=True,
                verbose_name="Camp Kickoff",
            ),
        ),
    ]
