# Generated by Django 5.2.14 on 2026-06-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0040_camp_ticket_type_full_week_adult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camp',
            options={'get_latest_by': 'camp', 'ordering': ['-title'], 'verbose_name': 'Camp', 'verbose_name_plural': 'Camps'},
        ),
    ]
