# Generated by Django 3.2.14 on 2022-07-18 09:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0007_default_location_and_hours_overlap_contraint'),
        ('teams', '0052_team_permission_set'),
        ('villages', '0012_village_approved'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(help_text='The collection of geometries for this object.', srid=4326)),
                ('name', models.CharField(help_text='The name of this geometry collection.', max_length=100)),
                ('description', models.TextField(help_text='Description of this geometry collection.')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_maps.geometry_set+', to='contenttypes.contenttype')),
                ('responsible_team', models.ForeignKey(help_text='The Team responsible for this geometry.', on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('geometry'), models.Model),
        ),
        migrations.CreateModel(
            name='VillageGeometry',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.geometry')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(help_text='The Village to which this geometry belongs', on_delete=django.db.models.deletion.PROTECT, related_name='geometries', to='villages.village')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('village_geometry'), 'maps.geometry', models.Model),
        ),
        migrations.CreateModel(
            name='FacilityGeometry',
            fields=[
                ('geometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.geometry')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(help_text='The Facility to which this geometry belongs', on_delete=django.db.models.deletion.PROTECT, related_name='geometries', to='facilities.facility')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('facility_geometry'), 'maps.geometry', models.Model),
        ),
    ]
