# Generated by Django 4.2.10 on 2024-08-19 06:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0036_camp_economy_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or description of this layer', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='The url slug for this layer. Leave blank to autogenerate one.', unique=True)),
                ('description', models.TextField(help_text='Description of this layer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or description of this feature', max_length=100)),
                ('description', models.TextField(help_text='Description of this feature')),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(help_text='Geometric data', srid=4326)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.layer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalLayer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or description of this layer', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='The url slug for this layer. Leave blank to autogenerate one.', unique=True)),
                ('description', models.TextField(help_text='Description of this layer')),
                ('url', models.URLField(help_text='URL of the GEOJSON layer', max_length=255)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camps.camp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
