# Generated by Django 4.2.10 on 2024-08-19 08:41

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0036_camp_economy_team'),
        ('maps', '0001_map_add_layer_and_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camps.camp'),
        ),
        migrations.AddField(
            model_name='layer',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='layer',
            name='icon',
            field=models.CharField(blank=True, default='list', help_text="Name of the fontawesome icon to use, excluding the 'fab fa-' or 'fas fa-' part.", max_length=100),
        ),
    ]
