# Generated by Django 4.2.14 on 2024-08-19 09:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_layer_camp_layer_color_layer_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
