# Generated by Django 4.2.16 on 2024-09-25 18:31
from __future__ import annotations

import colorfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_feature_layer_and_name_uniq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="color",
            field=colorfield.fields.ColorField(default="#000000FF", image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fab fa-list",
                help_text="Name of the fontawesome icon to use, including the 'fab fa-' or 'fas fa-' part.",
                max_length=100,
            ),
        ),
    ]
