# Generated by Django 4.2.21 on 2025-05-11 16:31

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0038_alter_permission_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maps", "0003_alter_feature_color_alter_feature_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLocationType",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Name of the user location type", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="The url slug for this user location type. Leave blank to autogenerate one.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-list",
                        help_text="Name of the fontawesome icon to use, including the 'fab fa-' or 'fas fa-' part.",
                        max_length=100,
                    ),
                ),
                (
                    "marker",
                    models.CharField(
                        choices=[
                            ("blueIcon", "Blue (#2A81CB)"),
                            ("goldIcon", "Gold (#FFD326)"),
                            ("redIcon", "Red (#CB2B3E)"),
                            ("greenIcon", "Green (#2AAD27)"),
                            ("orangeIcon", "Orange (#CB8427)"),
                            ("yellowIcon", "Yellow (#CAC428)"),
                            ("violetIcon", "Violet (#9C2BCB)"),
                            ("greyIcon", "Grey (#7B7B7B)"),
                            ("blackIcon", "Black (#3D3D3D)"),
                        ],
                        default="blueIcon",
                        help_text="The name/colour of the Leaflet marker to use for this User Location Type.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Name of the location", max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="The location.",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("data", models.JSONField(blank=True, help_text="JSON data field", max_length=10240, null=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_locations",
                        to="camps.camp",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Type of this location (extra types can be requested at the GIS team)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_locations",
                        to="maps.userlocationtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The django user this UserLocation belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_locations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
