# Generated by Django 4.2.14 on 2024-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_feature_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='color',
        ),
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, default='list', help_text="Name of the fontawesome icon to use, including the 'fab fa-' or 'fas fa-' part.", max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='processing',
            field=models.CharField(blank=True, help_text='Name of javascript function call for processing data from the topic', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='topic',
            field=models.CharField(blank=True, help_text='Name of the topic to update this feature', max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
