# Generated by Django 4.2.16 on 2024-09-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_group_alter_feature_layer_layer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='icon',
            field=models.CharField(blank=True, default='list', help_text="Name of the fontawesome icon to use, including the 'fab fa-' or 'fas fa-' part.", max_length=100),
        ),
    ]
