# Generated by Django 4.2.16 on 2024-09-23 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0052_team_permission_set'),
        ('maps', '0006_alter_layer_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallayer',
            name='responsible_team',
            field=models.ForeignKey(blank=True, help_text='The Team responsible for this Layer.', null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.team'),
        ),
        migrations.AddField(
            model_name='layer',
            name='responsible_team',
            field=models.ForeignKey(blank=True, help_text='The Team responsible for this Layer.', null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.team'),
        ),
        migrations.RemoveField(
            model_name='externallayer',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='camp',
        ),

    ]
