# Generated by Django 4.2.16 on 2024-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_externallayer_responsible_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='invisible',
            field=models.BooleanField(default=False, help_text='Is the layer invisible in the map view?'),
        ),
    ]
