# Generated by Django 2.1 on 2018-08-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
