# Generated by Django 1.11 on 2017-07-11 21:41

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("sponsors", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SponsorTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the tier (gold, silver, etc.)",
                        max_length=25,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A description of what the tier includes.",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sponsors.SponsorTier",
            ),
        ),
    ]
