# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sponsors", "0003_sponsortier_camp")]

    operations = [
        migrations.AddField(
            model_name="sponsortier",
            name="weight",
            field=models.IntegerField(
                default=0,
                help_text="This decides where on the list the tier will be shown. I.e.\n        gold should have a lower value than silver.",
            ),
        )
    ]
