# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_sponsortier_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, help_text='A URL to the sponsor.', null=True),
        ),
    ]
