# Generated by Django 1.10.5 on 2017-07-14 21:56
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("sponsors", "0004_sponsortier_weight")]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="A URL to the sponsor.",
                null=True,
            ),
        ),
    ]
