# Generated by Django 1.10.5 on 2018-03-18 08:06
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("sponsors", "0006_auto_20170715_1110")]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sponsors.SponsorTier",
            ),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="camp",
            field=models.ForeignKey(
                help_text="The camp this sponsor tier belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsor_tiers",
                to="camps.Camp",
            ),
        ),
    ]
