# Generated by Django 2.1.2 on 2018-11-18 13:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("sponsors", "0008_auto_20180815_1119")]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="logo_filename",
            field=models.CharField(
                blank=True,
                help_text="Filename of the logo",
                max_length=255,
                null=True,
            ),
        ),
    ]
