# Generated by Django 3.2.7 on 2021-09-02 10:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0012_auto_20190807_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="ticket_ready",
            field=models.BooleanField(
                default=False,
                help_text="Check when we are ready to generate and send tickets to this sponsor.",
            ),
        ),
    ]
