# Generated by Django 4.2.10 on 2024-07-11 20:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0013_alter_sponsor_ticket_ready_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsortier",
            name="tickets",
            field=models.IntegerField(
                blank=True,
                help_text="If set this is the number of full day tickets generated for a sponsor in this tier.",
                null=True,
            ),
        ),
    ]
