# Generated by Django 4.2.10 on 2024-07-11 20:46
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0014_alter_sponsortier_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsortier",
            name="oneday_tickets",
            field=models.IntegerField(
                default=0,
                help_text="The number of one day tickets generated for a sponsor in this tier.",
            ),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="tickets",
            field=models.IntegerField(
                default=0,
                help_text="The number of full day tickets generated for a sponsor in this tier.",
            ),
            preserve_default=False,
        ),
    ]
