# Generated by Django 4.2.10 on 2024-07-11 20:48
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0015_sponsortier_oneday_tickets_alter_sponsortier_tickets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sponsortier",
            old_name="tickets",
            new_name="week_tickets",
        ),
    ]
