# Generated by Django 4.2.10 on 2024-07-11 21:05
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0018_alter_sponsortier_oneday_tickets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="oneday_tickets",
            field=models.IntegerField(
                blank=True,
                help_text="The number of one day tickets to generate for this sponsor.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="week_tickets",
            field=models.IntegerField(
                blank=True,
                help_text="The number of full week tickets to generate for this sponsor.",
                null=True,
            ),
        ),
    ]
