# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0019_sponsor_oneday_tickets_sponsor_week_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sponsortier',
            options={'ordering': ['-created']},
        ),
    ]
