# Generated by Django 1.9.6 on 2016-05-30 22:23
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("news", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="newsitem",
            options={"ordering": ["-published_at"]},
        ),
    ]
