# Generated by Django 1.9.2 on 2016-06-05 21:26


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("news", "0002_auto_20160530_2223")]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
