# Generated by Django 1.9.6 on 2016-06-10 17:43
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("news", "0003_newsitem_slug")]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
