# Generated by Django 1.10.4 on 2016-12-20 11:27


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("news", "0005_auto_20160618_1902")]

    operations = [migrations.RemoveField(model_name="newsitem", name="public")]
