# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20161220_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
