# Generated by Django 1.10.4 on 2016-12-20 13:03


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("news", "0007_auto_20161220_1136")]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
