# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20160808_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='days',
            field=models.ManyToManyField(blank=True, to='camps.Day'),
        ),
    ]
