# Generated by Django 1.9.6 on 2016-05-10 20:02


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="orderproductrelation",
            name="handed_out",
            field=models.BooleanField(default=False),
        ),
    ]
