# Generated by Django 1.9.6 on 2016-05-15 16:04


import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0003_auto_20160513_0646")]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.ProductCategory",
            ),
        ),
    ]
