# Generated by Django 1.9.6 on 2016-05-15 16:14


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0004_auto_20160515_1604")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
