# Generated by Django 1.9.6 on 2016-05-15 21:57
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0006_ensure_slugs")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="open",
            field=models.NullBooleanField(
                default=True,
                help_text='Whether this order is open or not. "None" means closed.',
                verbose_name="Open?",
            ),
        ),
        migrations.RemoveField(model_name="order", name="finalized"),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set([("user", "open")]),
        ),
    ]
