# Generated by Django 1.9.2 on 2016-05-17 06:00
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0008_auto_20160516_0954")]

    operations = [
        migrations.AddField(
            model_name="epaycallback",
            name="md5valid",
            field=models.BooleanField(default=False),
        ),
    ]
