# Generated by Django 1.9.2 on 2016-05-17 13:13
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0009_epaycallback_md5valid")]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sent_to_customer", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.Order",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterModelOptions(
            name="epaycallback",
            options={
                "ordering": ["-created"],
                "verbose_name": "Epay Callback",
                "verbose_name_plural": "Epay Callbacks",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text=b"Is this product publicly available in the webshop?",
            ),
        ),
    ]
