# Generated by Django 1.9.2 on 2016-05-17 19:02
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0010_auto_20160517_1313")]

    operations = [
        migrations.RemoveField(model_name="product", name="public"),
        migrations.AddField(
            model_name="productcategory",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
