# Generated by Django 1.9.6 on 2016-05-25 17:02


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0013_ticket_qrcode_base64")]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="name",
            field=models.CharField(
                default="",
                help_text=b"Name of the person this ticket belongs to. This can be different from the buying user.",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
