# Generated by Django 1.9.6 on 2016-05-30 23:01


import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0021_ticket_email")]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="name",
            field=models.CharField(
                blank=True,
                help_text=b"Name of the person this ticket belongs to. This can be different from the buying user.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="shop.Order",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="shop.Product",
            ),
        ),
    ]
