# Generated by Django 1.10.3 on 2016-11-09 11:46
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0031_auto_20161109_1000")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_comment",
            field=models.TextField(
                default=b"",
                help_text="If you have any comments about the order please enter them here.",
                verbose_name="Customer comment",
            ),
        ),
    ]
