# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_customer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='camp',
        ),
    ]
