# Generated by Django 1.10.5 on 2017-03-19 21:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0036_auto_20170319_2155")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
