# Generated by Django 1.10.5 on 2017-05-07 08:00
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0041_auto_20170408_1104")]

    operations = [
        migrations.AlterField(
            model_name="coinifyapiinvoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coinify_api_invoices",
                to="shop.Order",
            ),
        ),
    ]
