# Generated by Django 1.10.5 on 2017-05-07 11:09

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0042_auto_20170507_1000")]

    operations = [
        migrations.CreateModel(
            name="CoinifyAPIRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("payload", django.contrib.postgres.fields.jsonb.JSONField()),
                ("response", models.TextField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coinify_api_requests",
                        to="shop.Order",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="coinifyapicallback",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coinify_api_callbacks",
                to="shop.Order",
            ),
        ),
    ]
