# Generated by Django 1.10.5 on 2017-05-07 17:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0045_auto_20170507_1648")]

    operations = [
        migrations.AddField(
            model_name="coinifyapirequest",
            name="method",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
