# Generated by Django 1.10.5 on 2017-05-22 17:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("shop", "0046_coinifyapirequest_method")]

    operations = [
        migrations.AlterField(
            model_name="coinifyapirequest",
            name="response",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
