# Generated by Django 1.10.5 on 2017-08-19 20:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("tickets", "0001_initial"), ("shop", "0047_auto_20170522_1942")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.TicketType",
            ),
        ),
    ]
