# Generated by Django 1.10.5 on 2017-09-14 18:34
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0048_product_ticket_type")]

    operations = [
        migrations.AddField(
            model_name="customorder",
            name="danish_vat",
            field=models.BooleanField(default=True, help_text="Danish VAT?"),
        ),
        migrations.AlterField(
            model_name="customorder",
            name="paid",
            field=models.BooleanField(
                default=False,
                help_text="Check when this custom order has been paid (or if it gets cancelled out by a Credit Note)",
                verbose_name="Paid?",
            ),
        ),
    ]
