# Generated by Django 1.10.5 on 2017-09-16 11:36
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0049_auto_20170914_2034")]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="customer",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Customer info if no user is selected",
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="text",
            field=models.TextField(
                help_text="Description of what this credit note covers",
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user this credit note belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditnotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
