# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-17 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20170916_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='danish_vat',
            field=models.BooleanField(default=True, help_text='Danish VAT?'),
        ),
    ]
