# Generated by Django 1.10.5 on 2017-10-03 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("shop", "0051_creditnote_danish_vat")]

    operations = [
        migrations.RemoveField(model_name="ticket", name="order"),
        migrations.RemoveField(model_name="ticket", name="product"),
        migrations.DeleteModel(name="Ticket"),
    ]
