# Generated by Django 2.0.4 on 2018-08-27 08:20
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0055_order_customer_address")]

    operations = [
        migrations.RemoveField(model_name="order", name="customer_address"),
        migrations.AddField(
            model_name="order",
            name="invoice_address",
            field=models.TextField(
                blank=True,
                help_text="The invoice address for this order. Leave blank to use the email associated with the logged in user.",
            ),
        ),
    ]
