# Generated by Django 2.0.4 on 2018-08-27 10:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("shop", "0056_auto_20180827_1020")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Any internal notes about this order can be entered here. They will not be printed on the invoice or shown to the customer in any way.",
            ),
        ),
    ]
