# Generated by Django 2.1.7 on 2019-07-08 21:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0057_order_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="proforma_invoices/",
            ),
        ),
    ]
