# Generated by Django 2.2.2 on 2019-07-18 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0058_order_pdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproductrelation",
            old_name="handed_out",
            new_name="ticket_generated",
        ),
    ]
