# Generated by Django 2.2.3 on 2019-12-16 22:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0059_auto_20190718_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Sorting weight. Heavier items sink to the bottom.",
            ),
        ),
    ]
