# Generated by Django 3.1 on 2020-08-11 00:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0060_productcategory_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinifyapicallback",
            name="headers",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="coinifyapicallback",
            name="payload",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="coinifyapiinvoice",
            name="invoicejson",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="coinifyapirequest",
            name="payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="coinifyapirequest",
            name="response",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="epaycallback",
            name="payload",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="open",
            field=models.BooleanField(
                default=True,
                help_text='Whether this shop order is open or not. "None" means closed.',
                null=True,
                verbose_name="Open?",
            ),
        ),
    ]
