# Generated by Django 3.1 on 2020-08-11 08:15
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0061_auto_20200811_0233"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="open",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text='Whether this shop order is open or not. "None" means closed.',
                null=True,
                verbose_name="Open?",
            ),
        ),
    ]
