# Generated by Django 3.1 on 2020-08-12 15:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0062_auto_20200811_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credit_card", "Credit card"),
                    ("blockchain", "Blockchain"),
                    ("bank_transfer", "Bank transfer"),
                    ("in_person", "In Person"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
