# Generated by Django 3.1 on 2020-10-17 00:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0063_auto_20200812_1732"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Internal comments for this product.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.IntegerField(
                default=0,
                help_text="The cost for this product, including VAT. Used for profit calculations in the economy system.",
            ),
        ),
    ]
