# Generated by Django 3.2.5 on 2021-08-03 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0064_add_product_comment_and_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epaypayment",
            options={
                "ordering": ["created"],
                "verbose_name": "Epay Payment",
                "verbose_name_plural": "Epay Payments",
            },
        ),
    ]
