# Generated by Django 3.2.7 on 2021-10-05 10:22
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0065_alter_epaypayment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproductrelation",
            name="refunded",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of items refunded from this OPR",
            ),
        ),
        migrations.AlterField(
            model_name="orderproductrelation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oprs",
                to="shop.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderproductrelation",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="The number of times this product has been bought on this order",
            ),
        ),
        migrations.AlterField(
            model_name="orderproductrelation",
            name="ticket_generated",
            field=models.BooleanField(
                default=False,
                help_text="True if the ticket(s) for this OPR have been generated, False if not.",
            ),
        ),
    ]
