# Generated by Django 3.2.7 on 2021-10-05 21:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0066_order_refunded"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="The Invoice this CreditNote relates to, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creditnotes",
                to="shop.invoice",
            ),
        ),
    ]
