# Generated by Django 3.2.8 on 2021-10-06 19:22

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_creditnote_invoice'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderproductrelation',
            constraint=models.CheckConstraint(check=models.Q(('refunded__lte', django.db.models.expressions.F('quantity'))), name='refund_less_or_equal_quantity'),
        ),
    ]
