# Generated by Django 3.2.12 on 2022-04-02 13:28
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0068_orderproductrelation_refund_less_or_equal_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this shop refund has been paid.",
                        verbose_name="Paid?",
                    ),
                ),
                (
                    "customer_comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="If you (the customer) have any comments about the refund please enter them here. This field is not currently being used.",
                        verbose_name="Customer comment",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Any internal notes about this Refund can be entered here. They will not be printed on the creditnote or shown to the customer in any way.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="RefundProductRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="The number of times this product is being refunded in this Refund",
                    ),
                ),
                (
                    "ticket_deleted",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time when ticket(s) related to this RefundProductRelation were deleted",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="orderproductrelation",
            name="refund_less_or_equal_quantity",
        ),
        migrations.RemoveField(
            model_name="orderproductrelation",
            name="refunded",
        ),
        migrations.AddField(
            model_name="orderproductrelation",
            name="price",
            field=models.IntegerField(
                blank=True,
                help_text="The price (per product, at the time of purchase, in DKK, including VAT).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderproductrelation",
            name="ticket_generated_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Generation time of the ticket(s) for this OPR. Blank if ticket(s) have not been generated yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderproductrelation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oprs",
                to="shop.order",
            ),
        ),
        migrations.AddField(
            model_name="refundproductrelation",
            name="opr",
            field=models.ForeignKey(
                help_text="The OPR which this RPR is refunding",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rprs",
                to="shop.orderproductrelation",
            ),
        ),
        migrations.AddField(
            model_name="refundproductrelation",
            name="refund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rprs",
                to="shop.refund",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                help_text="The Order this Refund is refunding (partially or fully)",
                related_name="refunds",
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.order",
            ),
        ),
    ]
