# Generated by Django 3.2.12 on 2022-04-02 13:31
from __future__ import annotations

from django.db import migrations


def fixup_opr(apps, schema_editor):
    """Loop over OrderProductRelations and fix a few things.

    - Set price (so we can do a Refund with the correct amount even if the price in the shop changed later)
    - Set ticket_generated_time to as close as we can get to the historical ticket creation time.
    """
    OrderProductRelation = apps.get_model("shop", "OrderProductRelation")
    for opr in OrderProductRelation.objects.all():
        # set price
        opr.price = opr.product.price
        # set ticket generated time
        if opr.shoptickets.exists():
            opr.ticket_generated_time = opr.shoptickets.first().created
        elif opr.ticket_generated:
            # tickets must have been refunded, use opr update time
            opr.ticket_generated_time = opr.updated
        opr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0069_refund"),
    ]

    operations = [
        migrations.RunPython(fixup_opr),
    ]
