# Generated by Django 3.2.12 on 2022-04-02 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0071_backfill_refunds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproductrelation",
            name="ticket_generated",
        ),
    ]
