# Generated by Django 3.2.12 on 2022-04-02 15:07
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0072_remove_orderproductrelation_ticket_generated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproductrelation",
            old_name="ticket_generated_time",
            new_name="ticket_generated",
        ),
    ]
