# Generated by Django 3.2.8 on 2022-04-03 13:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "shop",
            "0073_rename_ticket_generated_time_orderproductrelation_ticket_generated",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="invoice_address",
            field=models.TextField(
                blank=True,
                help_text="The invoice address for this refund. Leave blank to use the invoice address from the Order object.",
            ),
        ),
    ]
