# Generated by Django 3.2.12 on 2022-04-03 18:42
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0074_refund_invoice_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickPayAPIRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "Get"),
                            ("POST", "Post"),
                            ("PUT", "Put"),
                            ("PATCH", "Patch"),
                            ("DELETE", "Delete"),
                        ],
                        help_text="The HTTP method for this request",
                        max_length=10,
                    ),
                ),
                (
                    "endpoint",
                    models.TextField(help_text="The API endpoint for this request"),
                ),
                ("body", models.TextField(default="")),
                ("headers", models.JSONField(default=dict)),
                ("query", models.JSONField(default=dict)),
                ("raw", models.BooleanField(default=False)),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="The HTTP status code of the API response. This field is empty until we get an API response.",
                        null=True,
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True,
                        help_text="The API response headers. This field remains empty until we get an API response.",
                        null=True,
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        help_text="The API response body. This field remains empty until we get an API response.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quickpay_api_requests",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuickPayAPIObject",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.TextField(help_text="The type of this QuickPayAPIObject"),
                ),
                (
                    "object_body",
                    models.JSONField(help_text="The body of the QuickPay API object"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quickpay_api_objects",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuickPayAPICallback",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "headers",
                    models.JSONField(help_text="The HTTP headers of the callback"),
                ),
                ("body", models.JSONField(help_text="The JSON body of the callback")),
                (
                    "qpobject",
                    models.ForeignKey(
                        help_text="The QuickPayAPIObject this callback relates to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="callbacks",
                        to="shop.quickpayapiobject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
