# Generated by Django 3.2.12 on 2022-07-17 08:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0075_quickpayapicallback_quickpayapiobject_quickpayapirequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quickpayapirequest",
            name="raw",
        ),
        migrations.AlterField(
            model_name="quickpayapirequest",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="quickpayapirequest",
            name="headers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="quickpayapirequest",
            name="query",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
