# Generated by Django 3.2.14 on 2022-07-17 10:02
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0076_auto_20220717_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created this refund",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
