# Generated by Django 3.2.14 on 2022-07-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_creditnote_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='refund',
            field=models.OneToOneField(blank=True, help_text='The Refund this CreditNote relates to, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.refund'),
        ),
    ]
