# Generated by Django 3.2.14 on 2022-09-03 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0080_alter_creditnote_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this refund",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
