# Generated by Django 3.2.16 on 2022-12-05 20:44
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0082_alter_quickpayapirequest_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickpayapiobject",
            name="id",
            field=models.IntegerField(default=1, help_text="The object ID in QuickPays end", unique=True),
            preserve_default=False,
        ),
    ]
