# Generated by Django 4.2.1 on 2023-07-15 21:22

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0023_auto_20211006_2310"),
        ("shop", "0083_quickpayapiobject_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTypeProductRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number_of_tickets", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shop.product"
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ttprs",
                        to="tickets.tickettype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ticket_type_product_relation"
                ),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ticket_types",
            field=models.ManyToManyField(
                related_name="+",
                through="shop.TicketTypeProductRelation",
                to="tickets.tickettype",
            ),
        ),
    ]
