# Generated by Django 4.2.1 on 2023-07-19 10:36
from __future__ import annotations

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0083_quickpayapiobject_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProductRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number_of_tickets", models.IntegerField(default=1)),
                (
                    "bundle_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_product_relations",
                        to="shop.product",
                    ),
                ),
                (
                    "sub_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bundle_product_relations",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "sub_product_relation",
                ),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_products",
            field=models.ManyToManyField(
                related_name="+",
                through="shop.SubProductRelation",
                to="shop.product",
            ),
        ),
    ]
