# Generated by Django 4.2.1 on 2023-07-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0023_auto_20211006_2310"),
        ("shop", "0084_tickettypeproductrelation_product_ticket_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundproductrelation",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.tickettype",
            ),
        ),
    ]
