# Generated by Django 4.2.1 on 2023-07-16 20:13

from django.db import migrations


def migrate(apps, schema_editor):
    RefundProductRelation = apps.get_model("shop", "RefundProductRelation")

    for rpr in RefundProductRelation.objects.all():
        rpr.ticket_type = rpr.product.ticket_type
        rpr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0085_refundproductrelation_ticket_type"),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
