# Generated by Django 4.2.16 on 2024-10-11 08:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0085_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                help_text="Price of the product (in DKK, including VAT). The price can not be changed on an existing Product if the Product has been added to one or more orders/OPRs."
            ),
        ),
    ]
