# Generated by Django 4.2.16 on 2025-02-15 15:42
from __future__ import annotations

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0086_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinifyAPIPaymentIntent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("coinify_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("paymentintentjson", models.JSONField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coinify_api_payment_intents",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin("coinify_api_payment_intent"), models.Model),
        ),
    ]
