# Generated by Django 4.2.20 on 2025-04-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_coinifyapipaymentintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinifyapicallback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coinify_api_callbacks', to='shop.order'),
        ),
    ]
