# Generated by Django 4.2.21 on 2025-06-15 06:32
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0088_alter_coinifyapicallback_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproductrelation",
            name="label_printed",
            field=models.BooleanField(default=False, help_text="Is the label for this OPR printed"),
        ),
        migrations.AddField(
            model_name="orderproductrelation",
            name="ready_for_pickup",
            field=models.BooleanField(default=False, help_text="Is this OPR read for pickup"),
        ),
    ]
