# Generated by Django 5.2.9 on 2025-12-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_orderproductrelation_label_printed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_products',
            field=models.ManyToManyField(related_name='+', through='shop.SubProductRelation', through_fields=('bundle_product', 'sub_product'), to='shop.product'),
        ),
    ]
