# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_alter_product_sub_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinifyapicallback',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='coinifyapiinvoice',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='coinifyapipaymentintent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='coinifyapirequest',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='customorder',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='orderproductrelation',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='quickpayapicallback',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='quickpayapiobject',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='quickpayapirequest',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='refundproductrelation',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='subproductrelation',
            options={'ordering': ['-created']},
        ),
    ]
