# Generated by Django 3.0.3 on 2020-03-10 11:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0003_location_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitytype",
            name="marker",
            field=models.CharField(
                choices=[
                    ("blueIcon", "Blue (#2A81CB)"),
                    ("goldIcon", "Gold (#FFD326)"),
                    ("redIcon", "Red (#CB2B3E)"),
                    ("greenIcon", "Green (#2AAD27)"),
                    ("orangeIcon", "Orange (#CB8427)"),
                    ("yellowIcon", "Yellow (#CAC428)"),
                    ("violetIcon", "Violet (#9C2BCB)"),
                    ("greyIcon", "Grey (#7B7B7B)"),
                    ("blackIcon", "Black (#3D3D3D)"),
                ],
                default="blueIcon",
                help_text="The name/colour of the Leaflet marker to use for this facility type.",
                max_length=10,
            ),
        ),
    ]
