# Generated by Django 3.0.3 on 2020-06-16 21:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0005_facilityopeninghours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(9.93891, 55.38562),
                help_text="The location of this facility",
                srid=4326,
            ),
        ),
    ]
