# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_default_location_and_hours_overlap_contraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='facilityfeedback',
            options={'ordering': ['-created']},
        ),
    ]
