version: '3.7'
services:
    app:
        image: app
        build:
          context: ../
          dockerfile: docker/Dockerfile
        ports:
          - "${web_port}:8000"
        tty: true
        stdin_open: true
        command: python src/manage.py runserver 0.0.0.0:8000
        volumes:
          - ..:/app
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_HOST=db
          - POSTGRES_PORT=5432
        depends_on:
          - db
    invoiceworker:
      image: app
      build:
        context: ../
        dockerfile: docker/Dockerfile
      command: python src/manage.py run_managepy_worker shop.invoiceworker
      volumes:
        - ..:/app
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
      depends_on:
        - db
    db:
        build:
          context: postgis_container
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - ${db_port}:5432
