# Generated by Django 1.10.5 on 2017-03-27 20:08
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0020_camp_read_only"), ("teams", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="team", options={"ordering": ["name"]}),
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set([("slug", "camp")]),
        ),
    ]
