# Generated by Django 1.10.5 on 2017-04-01 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0002_auto_20170327_2208")]

    operations = [
        migrations.RenameField(
            model_name="teammember",
            old_name="leader",
            new_name="responsible",
        ),
    ]
