# Generated by Django 1.10.5 on 2017-04-02 11:31
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0005_auto_20170402_1331")]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="membersnew",
            new_name="members",
        ),
        migrations.AlterField(
            model_name="team",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="teams.TeamArea",
            ),
        ),
    ]
