# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("teams", "0006_auto_20170402_1331")]

    operations = [
        migrations.AddField(
            model_name="teamarea",
            name="description",
            field=models.TextField(default=""),
        )
    ]
