# Generated by Django 1.10.5 on 2017-04-02 12:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0006_auto_20170402_1331")]

    operations = [
        migrations.AddField(
            model_name="teamarea",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
