# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_teamarea_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='needs_members',
            field=models.BooleanField(default=True),
        ),
    ]
