# Generated by Django 1.10.5 on 2017-04-02 13:57
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0007_teamarea_description")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="needs_members",
            field=models.BooleanField(default=True),
        ),
    ]
