# Generated by Django 1.10.5 on 2017-04-02 14:07
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0009_auto_20170402_1607")]

    operations = [migrations.RemoveField(model_name="team", name="members")]
