# Generated by Django 1.10.5 on 2017-04-02 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0010_remove_team_members")]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="membersnew",
            new_name="members",
        ),
    ]
