# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("teams", "0011_auto_20170402_1608")]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="responsible",
            field=models.BooleanField(default=False),
        )
    ]
