# Generated by Django 1.10.5 on 2017-04-02 21:26
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0011_auto_20170402_1608")]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="responsible",
            field=models.BooleanField(default=False),
        ),
    ]
