# Generated by Django 1.10.5 on 2017-05-23 18:46
from __future__ import annotations

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0012_teammember_responsible")]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammember",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teammember",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
