# Generated by Django 1.10.5 on 2017-05-23 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0013_auto_20170523_2046")]

    operations = [migrations.RemoveField(model_name="teammember", name="deleted")]
