# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("teams", "0014_remove_teammember_deleted")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="mailing_list",
            field=models.EmailField(blank=True, max_length=254),
        )
    ]
