# Generated by Django 1.10.5 on 2017-07-11 20:47

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0015_team_mailing_list")]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="camps.Camp",
            ),
        ),
    ]
