# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20171122_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='guide',
            field=models.TextField(blank=True, default='\n# Preparations\n\n...\n\n# Camp setup\n\n...\n\n# During camp\n\n...\n\n# Takedown\n\n...\n\n# Notes for next year\n\n 1. Remember to take notes\n 1. ...\n', help_text='HowTo guide for this year (and next year)', verbose_name='team guide (Markdown)'),
        ),
    ]
