# Generated by Django 1.10.5 on 2018-03-18 08:06
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0020_auto_20180304_1233")]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="teams.Team",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teamtask",
            name="team",
            field=models.ForeignKey(
                help_text="The team this task belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="teams.Team",
            ),
        ),
    ]
