# Generated by Django 1.10.5 on 2018-03-18 11:45

from django.db import migrations


def populate_team_shortslugs(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    for team in Team.objects.all():
        if not team.shortslug:
            team.shortslug = team.slug
            team.save()


class Migration(migrations.Migration):
    dependencies = [("teams", "0023_auto_20180318_1256")]

    operations = [migrations.RunPython(populate_team_shortslugs)]
