# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_populate_shortslugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='shortslug',
            field=models.SlugField(help_text='Abbreviated version of the slug. Used in places like IRC channel names where space is limited'),
        ),
    ]
