# Generated by Django 1.10.5 on 2018-03-31 12:16
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0027_fixup_teams")]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="teams.TeamArea",
            ),
        ),
    ]
