# Generated by Django 1.10.5 on 2018-03-31 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0028_auto_20180331_1416")]

    operations = [migrations.RemoveField(model_name="team", name="area")]
