# Generated by Django 1.10.5 on 2018-04-02 13:14
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0029_remove_team_area")]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="irc_channel_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Team IRC channel. Leave blank to generate channel name automatically, based on camp shortslug and team shortslug.",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="irc_channel_private",
            field=models.BooleanField(
                default=True,
                help_text="Check to make the IRC channel secret and +i (private for team members only using an ACL). Leave unchecked to make the IRC channel public and open for everyone.",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="needs_members",
            field=models.BooleanField(
                default=True,
                help_text="Check to indicate that this team needs more members",
            ),
        ),
    ]
