# Generated by Django 1.10.5 on 2018-04-02 19:48

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0031_auto_20180402_2146")]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="camps.Camp",
            ),
        ),
    ]
