# Generated by Django 1.10.5 on 2018-04-02 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0033_auto_20180402_2204")]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["-responsible", "approved"]},
        ),
    ]
