# Generated by Django 1.10.5 on 2018-04-03 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0025_auto_20180318_1250"),
        ("teams", "0035_auto_20180402_2344"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together=set([("slug", "camp"), ("name", "camp")]),
        ),
    ]
