# Generated by Django 1.10.5 on 2018-04-12 15:46

from django.db import migrations


def fix_irc_channels(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    for team in Team.objects.filter(irc_channel=True):
        print("fixing irc channel for team %s" % team.name)
        if team.irc_channel_private:
            team.private_irc_channel_name = team.irc_channel_name
            if team.irc_channel_managed:
                team.private_irc_channel_managed = True
                team.private_irc_channel_bot = True
        else:
            team.public_irc_channel_name = team.irc_channel_name
            if team.irc_channel_managed:
                team.public_irc_channel_managed = True
                team.public_irc_channel_bot = True
        team.save()


class Migration(migrations.Migration):
    dependencies = [("teams", "0038_auto_20180412_1844")]

    operations = [migrations.RunPython(fix_irc_channels)]
