# Generated by Django 2.0.4 on 2018-08-04 14:41

import django.contrib.postgres.fields.ranges
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0042_auto_20180413_1933")]

    operations = [
        migrations.AddField(
            model_name="teamtask",
            name="completed",
            field=models.BooleanField(
                default=False,
                help_text="Check to mark this task as completed.",
            ),
        ),
        migrations.AddField(
            model_name="teamtask",
            name="when",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True,
                help_text="When does this task need to be started and/or finished?",
                null=True,
            ),
        ),
    ]
