# Generated by Django 2.0.4 on 2018-07-02 20:07
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("teams", "0043_auto_20180702_1338")]

    operations = [
        migrations.AlterField(
            model_name="teamshift",
            name="team_members",
            field=models.ManyToManyField(blank=True, to="teams.TeamMember"),
        ),
    ]
