# Generated by Django 2.0.4 on 2018-08-05 09:31
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0044_auto_20180702_1507"),
        ("teams", "0043_auto_20180804_1641"),
    ]

    operations = []
