# Generated by Django 2.1 on 2018-08-14 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0047_taskcomment")]

    operations = [
        migrations.RenameField(
            model_name="taskcomment",
            old_name="content",
            new_name="comment",
        ),
    ]
