# Generated by Django 2.1 on 2018-08-15 09:19
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("teams", "0048_auto_20180814_1950")]

    operations = [
        migrations.AlterModelOptions(
            name="teamtask",
            options={"ordering": ["completed", "when", "name"]},
        ),
    ]
