# Generated by Django 3.0.3 on 2020-02-19 19:08
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0051_auto_20190312_1129"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="permission_set",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of this Teams set of permissions. Must be a value from camps.models.Permission.Meta.permissions.",
                max_length=100,
            ),
        ),
    ]
