# Generated by Django 4.2.16 on 2024-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0052_team_permission_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='private_signal_channel_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='public_signal_channel_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
