# Generated by Django 4.2 on 2023-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0052_team_permission_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="signal_group",
            field=models.CharField(
                blank=True,
                help_text="The private Signal group for this team. Will be shown to team members on the team page. Leave empty if the team has no Signal group.",
                max_length=1000,
                null=True,
                unique=True,
            ),
        ),
    ]
