# Generated by Django 4.2.16 on 2024-09-28 06:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("teams", "0052_team_permission_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["-lead", "-approved"]},
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="responsible",
            new_name="lead",
        ),
        migrations.RemoveField(
            model_name="team",
            name="permission_set",
        ),
        migrations.AddField(
            model_name="team",
            name="group",
            field=models.OneToOneField(
                blank=True,
                help_text="The django group carrying the team permissions for this team.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
    ]
