# Generated by Django 4.2.16 on 2024-10-05 15:14
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0054_create_team_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="private_signal_channel_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="public_signal_channel_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
