# Generated by Django 4.2.21 on 2025-06-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0055_team_private_signal_channel_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.OneToOneField(help_text='The django group carrying the team permissions for this team.', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
