# Generated by Django 4.2.21 on 2025-06-08 09:27

from django.db import migrations

def rename_team_groups(apps, schema_editor) -> None:
    Team = apps.get_model("teams", "Team")

    for team in Team.objects.filter(group_member__name__endswith="-team"):
        print(f"renaming group for team {team.name} for {team.camp.title}")
        group = team.group_member
        group.name = group.name + "-member"
        group.save()
        print("group renamed")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0057_rename_group_team_group_member'),
    ]

    operations = [
        migrations.RunPython(rename_team_groups),
    ]
