# Generated by Django 4.2.21 on 2025-06-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0059_team_facilitator_group_team_infopager_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='group_member',
            new_name='member_group',
        ),
    ]
