# Generated by Django 4.2.21 on 2025-06-08 11:35

from django.db import migrations
from django.conf import settings

def create_team_groups(apps, schema_editor) -> None:
    Team = apps.get_model("teams", "Team")
    Group = apps.get_model("auth", "Group")

    for team in Team.objects.all():
        for perm in settings.BORNHACK_TEAM_PERMISSIONS.keys():
            fk = f"{perm}_group"
            print(f"checking perm {perm} fk {fk} ...")
            if not hasattr(team, fk) or not getattr(team, fk):
                group, created = Group.objects.get_or_create(name=f"{team.camp.slug}-{team.slug}-team-{perm}")
                if created:
                    logger.info(f"Created group {group} for team {team}")
                setattr(team, fk, group)
        print(f"saving team {team.name} for {team.camp.title}")
        team.save()
    print("done")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0060_rename_group_member_team_member_group'),
    ]

    operations = [
        migrations.RunPython(create_team_groups),
    ]
