# Generated by Django 4.2.21 on 2025-06-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0062_alter_team_facilitator_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_group',
            field=models.OneToOneField(help_text='The django group carrying the team permissions for this team.', on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='auth.group'),
        ),
    ]
