# Generated by Django 4.2.21 on 2025-06-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0063_alter_team_member_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamShiftAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('for_sale', models.BooleanField(default=False, help_text='Is the shift assignment for sale?')),
                ('team_member', models.ForeignKey(help_text='The team member on shift', on_delete=django.db.models.deletion.CASCADE, to='teams.teammember')),
                ('team_shift', models.ForeignKey(help_text='The shift', on_delete=django.db.models.deletion.CASCADE, to='teams.teamshift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teamshift',
            name='team_members_new',
            field=models.ManyToManyField(blank=True, related_name='team_members_new', through='teams.TeamShiftAssignment', to='teams.teammember'),
        ),
    ]
