# Generated by Django 4.2.21 on 2025-12-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0063_alter_team_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facilitator_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team facilitator permissions for this team.', on_delete=django.db.models.deletion.PROTECT, related_name='team_facilitator', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='infopager_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team infopager permissions for this team.', on_delete=django.db.models.deletion.PROTECT, related_name='team_infopager', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lead_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team lead permissions for this team.', on_delete=django.db.models.deletion.PROTECT, related_name='team_lead', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mapper_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team mapper permissions for this team.', on_delete=django.db.models.deletion.PROTECT, related_name='team_mapper', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team permissions for this team.', on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pos_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team pos permissions for this team.', on_delete=django.db.models.deletion.PROTECT, related_name='team_pos', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tasker_group',
            field=models.OneToOneField(blank=True, help_text='The django group carrying the team tasker permissions for this team.', on_delete=django.db.models.deletion.PROTECT, related_name='team_tasker', to='auth.group'),
        ),
    ]
