# Generated by Django 5.2.9 on 2026-02-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phonebook", "0005_alter_dectregistration_ipei"),
        ("teams", "0064_alter_team_facilitator_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="public_dect_number",
            field=models.ForeignKey(
                blank=True,
                help_text="The public DECT for this team.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_team_numbers",
                to="phonebook.dectregistration",
            ),
        ),
    ]
