# Generated by Django 4.2.21 on 2025-06-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0065_teamshiftassignment_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamshift',
            name='team_members',
        ),
    ]
