# Generated by Django 4.2.21 on 2025-06-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0066_remove_teamshift_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamshift',
            old_name='team_members_new',
            new_name='team_members',
        ),
    ]
