# Generated by Django 4.2.21 on 2025-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0067_rename_team_members_new_teamshift_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamshift',
            name='team_members',
            field=models.ManyToManyField(blank=True, through='teams.TeamShiftAssignment', to='teams.teammember'),
        ),
    ]
