# Generated by Django 4.2.21 on 2025-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0068_alter_teamshift_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamshiftassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
