# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ircbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingircmessage',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 17, 49, 36, 925459, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
