# Generated by Django 1.10.5 on 2017-01-31 17:49
from __future__ import annotations

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("ircbot", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="outgoingircmessage",
            name="timeout",
            field=models.DateTimeField(
                default=datetime.datetime(2017, 1, 31, 17, 49, 36, 925459, tzinfo=datetime.UTC),
            ),
            preserve_default=False,
        ),
    ]
