# Generated by Django 1.10.5 on 2017-01-31 20:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("ircbot", "0002_outgoingircmessage_timeout")]

    operations = [
        migrations.AddField(
            model_name="outgoingircmessage",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
