# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircbot', '0002_outgoingircmessage_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingircmessage',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
