# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ircbot', '0003_outgoingircmessage_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingircmessage',
            options={'ordering': ['-created']},
        ),
    ]
