# Generated by Django 1.10.5 on 2017-02-18 10:48
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("info", "0002_auto_20161228_2312")]

    operations = [
        migrations.AlterModelOptions(
            name="infocategory",
            options={
                "ordering": ["weight", "headline"],
                "verbose_name_plural": "Info Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="infoitem",
            options={"ordering": ["weight", "headline"]},
        ),
    ]
