# Generated by Django 2.0.4 on 2018-05-20 16:13
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("info", "0005_add_teams_to_categories")]

    operations = [
        migrations.AlterField(
            model_name="infocategory",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team responsible for this info category.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="info_categories",
                to="teams.Team",
            ),
        ),
        migrations.AlterUniqueTogether(name="infocategory", unique_together=set()),
        migrations.RemoveField(model_name="infocategory", name="camp"),
    ]
