# Generated by Django 1.9.6 on 2016-07-05 21:54


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("villages", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="village", name="open"),
        migrations.AddField(
            model_name="village",
            name="private",
            field=models.BooleanField(
                default=True,
                help_text="Check if your village is privately organized",
            ),
        ),
    ]
