# Generated by Django 1.9.6 on 2016-07-05 21:59


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("villages", "0002_auto_20160705_2154")]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Check if your village is privately organized",
            ),
        ),
    ]
