# Generated by Django 1.9.6 on 2016-07-10 16:58


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("villages", "0003_auto_20160705_2159")]

    operations = [
        migrations.AddField(
            model_name="village",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
