# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 20:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("villages", "0004_village_deleted")]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="description",
            field=models.TextField(
                help_text="A descriptive text about your village. Markdown is supported."
            ),
        )
    ]
