# Generated by Django 1.10.4 on 2016-12-28 22:08
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0011_auto_20161228_1750"),
        ("villages", "0006_remove_village_camp"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="camp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camps.Camp",
            ),
        ),
    ]
