# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 22:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("villages", "0007_village_camp")]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="camps.Camp"
            ),
        )
    ]
