# Generated by Django 1.10.4 on 2016-12-28 22:09
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("villages", "0007_village_camp")]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="camps.Camp",
            ),
        ),
    ]
