# Generated by Django 1.10.4 on 2016-12-29 21:43


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("villages", "0008_auto_20161228_2209")]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Check if your village is invite only. Leave unchecked to welcome strangers.",
            ),
        ),
    ]
