# Generated by Django 1.10.5 on 2018-03-18 08:06
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("villages", "0010_auto_20170318_1506")]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="camps.Camp",
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
