# Generated by Django 3.2.12 on 2022-07-11 23:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("villages", "0011_auto_20180318_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
