# Generated by Django 4.2.14 on 2024-08-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0012_village_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ('name',)},
        ),
    ]
