# Generated by Django 4.2.21 on 2025-05-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0014_alter_village_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ('name',)},
        ),
    ]
