# Generated by Django 4.2.21 on 2025-06-14 11:13
from __future__ import annotations

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("villages", "0015_alter_village_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="The location of this village.",
                null=True,
                srid=4326,
            ),
        ),
    ]
