# Generated by Django 2.0.4 on 2018-08-19 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tokens", "0003_token_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tokenfind",
            unique_together={("user", "token")},
        ),
    ]
