# Generated by Django 2.1.7 on 2019-03-27 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tokens", "0004_auto_20180819_1743")]

    operations = [
        migrations.AlterModelOptions(name="token", options={"ordering": ["camp"]}),
    ]
