# Generated by Django 3.1 on 2020-08-17 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tokens", "0005_auto_20190327_2025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenfind",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_finds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
