# Generated by Django 3.2.14 on 2022-07-17 14:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0006_set_tokenfind_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="An active token is listed and can be found by players, an inactive token is unlisted and returns an error saying 'valid but inactive token found' to players who find it.",
            ),
        ),
    ]
