# Generated by Django 3.2.14 on 2022-07-17 16:03

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0008_alter_token_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="valid_when",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True,
                db_index=True,
                help_text="Token valid start/end time. YYYY-MM-DD HH:MM:SS. Optional.",
                null=True,
            ),
        ),
    ]
