# Generated by Django 4.2.21 on 2025-06-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0038_alter_permission_options"),
        ("tokens", "0009_token_valid_when"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("camp", "token")},
        ),
    ]
