# Generated by Django 4.2.21 on 2025-06-12 13:10
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0010_alter_token_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "TokenCategory",
                "verbose_name_plural": "TokenCategories",
            },
        ),
        migrations.RenameField(
            model_name="token",
            old_name="category",
            new_name="hint",
        ),
    ]
