# Generated by Django 4.2.21 on 2025-06-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0011_tokencategory_rename_category_token_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="category",
            field=models.ForeignKey(
                help_text="Token category",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tokens.tokencategory",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="hint",
            field=models.TextField(help_text="The hint for this token"),
        ),
    ]
