# Generated by Django 4.2.21 on 2025-06-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0012_token_category_alter_token_hint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokencategory",
            options={
                "verbose_name": "Token category",
                "verbose_name_plural": "Token categories",
            },
        ),
    ]
