# Generated by Django 4.2.21 on 2025-07-07 12:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0012_token_category_alter_token_hint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokencategory",
            options={
                "verbose_name": "Token category",
                "verbose_name_plural": "Token categories",
            },
        ),
        migrations.AddField(
            model_name="tokencategory",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tokencategory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="description",
            field=models.TextField(
                help_text="The description of the token (not visible to players until they find the token)"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="hint",
            field=models.TextField(
                help_text="The hint for this token (always visible to players)"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                help_text="The secret token (^[0-9a-zA-Z\\.@]{12,32}$)",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z\\.@]{12,32}$",
                        "The token did not match the regex of 12-32 characters, with (letters, numbers, dot(s) and @)",
                    )
                ],
            ),
        ),
    ]
