# Generated by Django 4.2.21 on 2025-06-24 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0013_alter_tokencategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokencategory",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tokencategory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
