# Generated by Django 4.2.21 on 2025-06-29 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0014_tokencategory_created_tokencategory_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="description",
            field=models.TextField(
                help_text="The description of the token (not visible to players until they find the token)"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="hint",
            field=models.TextField(
                help_text="The hint for this token (always visible to players)"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                help_text="The secret token (^[0-9a-zA-Z\\.@]{12,32}$)",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z\\.@]{12,32}$",
                        "The token did not match the regex of 12-32 characters, with (letters, numbers, dot(s) and @)",
                    )
                ],
            ),
        ),
    ]
