from __future__ import annotations

DATE_FORMAT = "l, M jS, Y"
# DATE_INPUT_FORMATS
DATETIME_FORMAT = "l, M jS, Y, H:i (e)"
# DATETIME_INPUT_FORMATS
# DECIMAL_SEPARATOR
# FIRST_DAY_OF_WEEK
# MONTH_DAY_FORMAT
# NUMBER_GROUPING
SHORT_DATE_FORMAT = "Ymd"
# SHORT_DATETIME_FORMAT
# THOUSAND_SEPARATOR
TIME_FORMAT = "H:i"
# TIME_INPUT_FORMATS
# YEAR_MONTH_FORMAT
