# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20160529_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
    ]
