# Generated by Django 1.10.5 on 2018-03-25 14:16

from django.db import migrations


def create_eventtype(apps, schema_editor):
    Type = apps.get_model("events", "Type")
    Type.objects.create(name="ticket_created")


class Migration(migrations.Migration):
    dependencies = [("events", "0002_create_eventtype")]

    operations = [migrations.RunPython(create_eventtype)]
