# Generated by Django 1.10.5 on 2018-04-03 10:28
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("events", "0003_create_another_eventtype")]

    operations = [
        migrations.AddField(
            model_name="type",
            name="email_notification",
            field=models.BooleanField(
                default=False,
                help_text="Check to send email notifications for this type of event.",
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="irc_notification",
            field=models.BooleanField(
                default=False,
                help_text="Check to send IRC notifications for this type of event.",
            ),
        ),
    ]
