# Generated by Django 1.10.5 on 2018-03-25 14:16
from __future__ import annotations

from django.db import migrations


def create_eventtype(apps, schema_editor):
    Type = apps.get_model("events", "Type")
    Type.objects.create(name="ticket_stats")


class Migration(migrations.Migration):
    dependencies = [("events", "0004_auto_20180403_1228")]
    operations = [migrations.RunPython(create_eventtype)]
