# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_create_another_eventtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routing',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-created']},
        ),
    ]
