# Generated by Django 1.10.5 on 2017-04-13 15:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0002_profile_description")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your name or handle",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Please include any info you think could be relevant, like drivers license, first aid certificates, crafts, skills and previous experience.",
            ),
        ),
    ]
