# Generated by Django 1.10.5 on 2018-04-03 00:01
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0008_auto_20180325_2022")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickserv_username",
            field=models.CharField(
                blank=True,
                help_text="Your NickServ username is used to manage team IRC channel access lists.",
                max_length=50,
            ),
        ),
    ]
