# Generated by Django 1.10.5 on 2018-04-11 21:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0009_profile_nickserv_username")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickserv_username",
            field=models.CharField(
                blank=True,
                help_text="Your NickServ username is used to manage team IRC channel access lists. Make sure you register with NickServ _before_ you enter the username here!",
                max_length=50,
            ),
        ),
    ]
