# Generated by Django 4.2.16 on 2024-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180411_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default (Auto)'), ('slate', 'Slate'), ('solar', 'Solar')], default='default', max_length=20),
        ),
    ]
