# Generated by Django 4.2.16 on 2024-09-28 09:06
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_auto_20180411_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your name or handle (only visible to team leads and orga)",
                max_length=200,
            ),
        ),
    ]
