# Generated by Django 4.2.16 on 2024-10-06 08:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_profile_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("default", "Default (Auto)"), ("light", "Light"), ("slate", "Slate"), ("solar", "Solar")],
                default="default",
                max_length=20,
            ),
        ),
    ]
