# Generated by Django 4.2.19 on 2025-04-07 14:30

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_alter_profile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phonenumber",
            field=models.PositiveSmallIntegerField(
                help_text="The phonenumber you can be reached on. This field can be updated automatically when registering a DECT number in the phonebook.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
    ]
