# Generated by Django 4.2.19 on 2025-04-08 13:44
from __future__ import annotations

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_profile_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Your location at BornHack. This value is available on public maps.",
                null=True,
                srid=4326,
            ),
        ),
    ]
