# Generated by Django 4.2.20 on 2025-04-08 14:20

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(9.93891, 55.38562), help_text='Your location at BornHack. This value is available on public maps.', null=True, srid=4326),
        ),
    ]
