# Generated by Django 4.2.20 on 2025-04-08 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Your location at BornHack. This value is available on public maps.",
                null=True,
                srid=4326,
            ),
        ),
    ]
