# Generated by Django 4.2.20 on 2025-04-28 15:00
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_alter_profile_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_username",
            field=models.SlugField(
                blank=True,
                help_text="When using your BornHack account to login to other sites with OIDC this value is served as the OIDC standard claim 'preferred_username'. You can set this to the username you would prefer to use on remote sites where you login with your BornHack account.",
            ),
        ),
    ]
