# Generated by Django 4.2.20 on 2025-05-11 07:26
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_profile_preferred_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
    ]
