# Generated by Django 5.2.9 on 2026-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_remove_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What can we call you? (visible to any team member aka. volunteer, but not the public)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="public_credit_name",
            field=models.CharField(
                blank=True,
                help_text="The name you want to appear in the credits section of the public website (on Team and People pages). Leave this empty if you want your name hidden on the public webpages.",
                max_length=100,
            ),
        ),
    ]
