# Generated by Django 2.1 on 2018-08-20 13:51

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("camps", "0030_camp_light_text"), ("feedback", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="camp",
            field=models.ForeignKey(
                default="30fd754f-dae4-460f-8128-6638fb29ab2d",
                on_delete=django.db.models.deletion.PROTECT,
                to="camps.Camp",
            ),
            preserve_default=False,
        ),
    ]
