# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20220805_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
    ]
