# Generated by Django 5.2.9 on 2025-12-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_alter_feedback_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="state",
            field=models.CharField(
                choices=[
                    ("reviewed", "Reviewed"),
                    ("spam", "Spam"),
                    ("unprocessed", "Unprocessed"),
                ],
                default="unprocessed",
                help_text="Set state of the feedback",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback",
            field=models.TextField(
                help_text="Enter your feedback for this year's event"
            ),
        ),
    ]
