# Generated by Django 5.2.9 on 2026-01-20 22:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0040_camp_ticket_type_full_week_adult_and_more"),
        ("feedback", "0005_feedback_state_alter_feedback_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="CampFeedback",
        ),
    ]
