# Generated by Django 5.2.9 on 2026-01-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_rename_feedback_campfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campfeedback",
            name="feedback",
            field=models.TextField(
                help_text="Enter your feedback for this year's camp"
            ),
        ),
    ]
