# Generated by Django 1.10.5 on 2017-05-21 16:08
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("utils", "0001_initial")]

    operations = [migrations.RemoveField(model_name="outgoingemail", name="recipient")]
