# Generated by Django 1.10.5 on 2017-05-21 17:32

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("utils", "0002_remove_outgoingemail_recipient")]

    operations = [
        migrations.AddField(
            model_name="outgoingemail",
            name="bcc_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="outgoingemail",
            name="cc_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="outgoingemail",
            name="to_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
