# Generated by Django 3.0.3 on 2020-06-22 13:44
from __future__ import annotations

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0052_team_permission_set"),
        ("utils", "0004_uuidtaggeditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingemail",
            name="hold",
            field=models.BooleanField(
                default=False,
                help_text="Hold (do not send) this email. Uncheck to send.",
            ),
        ),
        migrations.AddField(
            model_name="outgoingemail",
            name="responsible_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The Team responsible for this email.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="teams.Team",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="The attachment for this email. Optional.",
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="bcc_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                help_text="The Bcc: recipients",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="cc_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                help_text="The Cc: recipients",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="html_template",
            field=models.TextField(
                blank=True,
                help_text="The HTML body of the email (optional).",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="processed",
            field=models.BooleanField(
                default=False,
                help_text="Unchecked before the email is sent, checked after the email has been sent.",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="sender",
            field=models.CharField(help_text="The email sender.", max_length=500),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="subject",
            field=models.CharField(
                help_text="The subject of the e-mail",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="text_template",
            field=models.TextField(help_text="The plaintext body of the email."),
        ),
        migrations.AlterField(
            model_name="outgoingemail",
            name="to_recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                blank=True,
                help_text="The To: recipients",
                null=True,
                size=None,
            ),
        ),
    ]
