# Generated by Django 4.2.16 on 2024-10-06 08:39
from __future__ import annotations

import uuid

from django.db import migrations


def convert_usernames_to_uuids(apps, schema_editor):
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        username = user.username
        user.username = uuid.uuid4()
        user.save()
        print(username, user.username)
    print("done")


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0006_alter_uuidtaggeditem_content_type_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_usernames_to_uuids),
    ]
