# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_convert_usernames_to_uuids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingemail',
            options={'ordering': ['-created']},
        ),
    ]
