# Generated by Django 1.9.6 on 2016-08-04 17:05
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="color",
            field=models.CharField(default="#ff0000", max_length=50),
            preserve_default=False,
        ),
    ]
