# Generated by Django 1.9.6 on 2016-08-04 17:11


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0002_eventtype_color")]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="light_writing",
            field=models.BooleanField(default=False),
        ),
    ]
