# Generated by Django 1.9.6 on 2016-08-07 13:12
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0004_auto_20160804_1712")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(default="", blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="speaker",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="speakers",
                related_query_name="speaker",
                to="program.Event",
            ),
        ),
    ]
