# Generated by Django 1.9.6 on 2016-08-07 13:33


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("program", "0006_auto_20160807_1320")]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="description",
            new_name="abstract",
        ),
    ]
