# Generated by Django 1.9.6 on 2016-08-27 07:52


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0008_auto_20160808_1747")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="days",
            field=models.ManyToManyField(blank=True, to="camps.Day"),
        ),
    ]
