# Generated by Django 1.10.4 on 2016-12-12 18:09
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0007_auto_20161212_1803"),
        ("program", "0009_auto_20160827_0752"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={"ordering": ["start"]},
        ),
        migrations.RemoveField(model_name="event", name="days"),
        migrations.RemoveField(model_name="event", name="end"),
        migrations.RemoveField(model_name="event", name="start"),
        migrations.AddField(
            model_name="event",
            name="camp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="camps.Camp",
            ),
        ),
        migrations.AddField(
            model_name="eventinstance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="program.Event",
            ),
        ),
    ]
