# Generated by Django 1.10.5 on 2017-01-21 12:12


import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0012_auto_20161229_2150")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="camp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="camps.Camp",
            ),
        ),
    ]
