# Generated by Django 1.10.5 on 2017-01-31 17:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0015_auto_20170128_1841")]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
