# Generated by Django 1.10.5 on 2017-02-01 23:18
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0016_auto_20170131_1849")]

    operations = [
        migrations.AddField(
            model_name="eventinstance",
            name="notifications_sent",
            field=models.BooleanField(default=False),
        ),
    ]
