# Generated by Django 1.10.5 on 2017-02-02 12:29
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0017_eventinstance_notifications_sent")]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="notifications",
            field=models.BooleanField(default=False),
        ),
    ]
