# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_eventinstance_notifications_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
