# Generated by Django 1.10.5 on 2017-02-18 10:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0021_auto_20170205_2130")]

    operations = [
        migrations.RenameField(
            model_name="speaker",
            old_name="picture",
            new_name="picture_large",
        ),
        migrations.AddField(
            model_name="speaker",
            name="picture_small",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
