# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:43
from __future__ import unicode_literals

from django.db import migrations, models

import program.models


class Migration(migrations.Migration):

    dependencies = [("program", "0022_auto_20170218_1148")]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="picture_large",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=program.models.get_speaker_picture_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="picture_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=program.models.get_speaker_picture_upload_path,
            ),
        ),
    ]
