# Generated by Django 1.10.5 on 2017-03-06 18:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0024_auto_20170222_1629")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="video_recording",
            field=models.BooleanField(
                default=True,
                help_text="Whether the event will be video recorded or not.",
            ),
        ),
    ]
