# Generated by Django 1.10.5 on 2017-03-12 14:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0030_auto_20170312_1230")]

    operations = [
        migrations.RemoveField(model_name="speaker", name="user"),
        migrations.AddField(
            model_name="eventsubmission",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="The speaker(s) for this event",
                to="program.SpeakerSubmission",
            ),
        ),
    ]
