# Generated by Django 1.10.5 on 2017-03-12 14:56
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0031_auto_20170312_1529")]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Check to permit users to submit events of this type",
            ),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pick the speaker(s) for this event",
                to="program.SpeakerSubmission",
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="color",
            field=models.CharField(
                help_text="The background color of this event type",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="light_text",
            field=models.BooleanField(
                default=False,
                help_text="Check if this event type should use white text color",
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name",
            field=models.CharField(
                help_text="The name of this event type",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="notifications",
            field=models.BooleanField(
                default=False,
                help_text="Check to send notifications for this event type",
            ),
        ),
    ]
