# Generated by Django 1.10.5 on 2017-03-26 11:50
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0036_auto_20170316_0004")]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="include_in_event_list",
            field=models.BooleanField(
                default=True,
                help_text="Include events of this type in the event list?",
            ),
        ),
    ]
