# Generated by Django 1.10.5 on 2017-04-30 12:08
from __future__ import annotations

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("program", "0038_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                help_text="The event(s) this speaker is anchoring",
                related_name="speakers",
                to="program.Event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together=set([("user", "event_instance")]),
        ),
    ]
