# Generated by Django 1.10.5 on 2017-07-15 13:47
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0041_auto_20170711_2248")]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="submission_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes for the event. Only visible to the submitting user and the BornHack organisers.",
            ),
        ),
        migrations.AddField(
            model_name="speakerproposal",
            name="submission_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes for the event. Only visible to the submitting user and the BornHack organisers.",
            ),
        ),
    ]
