# Generated by Django 1.10.5 on 2017-08-01 13:26
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0042_auto_20170715_1547")]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="submission_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes for this event. Only visible to the submitting user and the BornHack organisers.",
            ),
        ),
        migrations.AlterField(
            model_name="speakerproposal",
            name="submission_notes",
            field=models.TextField(
                blank=True,
                help_text="Private notes for this speaker. Only visible to the submitting user and the BornHack organisers.",
            ),
        ),
    ]
