# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0045_event_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='picture_large',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='speakerproposal',
            old_name='picture_large',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='picture_small',
        ),
        migrations.RemoveField(
            model_name='speakerproposal',
            name='picture_small',
        ),
    ]
