# Generated by Django 2.0.4 on 2018-05-12 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("program", "0049_add_event_tracks")]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("track", "title"), ("track", "slug")},
        ),
        migrations.RemoveField(model_name="eventproposal", name="camp"),
        migrations.RemoveField(model_name="event", name="camp"),
    ]
