# Generated by Django 2.0.4 on 2018-06-03 13:25

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0060_auto_20180603_1455")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="proposal",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="The event proposal object this event was created from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="program.EventProposal",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="proposal",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="The speaker proposal object this speaker was created from",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="program.SpeakerProposal",
            ),
        ),
    ]
