# Generated by Django 2.0.4 on 2018-07-17 15:20
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0061_auto_20180603_1525")]

    operations = [
        migrations.AlterField(
            model_name="urltype",
            name="icon",
            field=models.CharField(
                default="fas fa-link",
                help_text="Name of the fontawesome icon to use, including the 'fab fa-' or 'fas fa-' part.",
                max_length=100,
            ),
        ),
    ]
