# Generated by Django 2.0.4 on 2018-08-09 13:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0062_auto_20180717_1720")]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="allow_video_recording",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to avoid video recording.",
            ),
        ),
    ]
