# Generated by Django 2.1 on 2018-08-10 15:48
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0063_auto_20180809_1525")]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="allow_video_recording",
            field=models.BooleanField(
                default=False,
                help_text="Uncheck to avoid video recording.",
            ),
        ),
    ]
