# Generated by Django 2.1 on 2018-08-18 11:42
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0064_auto_20180810_1748")]

    operations = [
        migrations.AddField(
            model_name="speakerproposal",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The email of the speaker (defaults to the logged in user if empty.",
                max_length=150,
                null=True,
            ),
        ),
    ]
