# Generated by Django 2.1 on 2018-08-18 12:08
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("program", "0065_speakerproposal_email")]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="The email of the speaker.",
                max_length=150,
                null=True,
            ),
        ),
    ]
