# Generated by Django 2.1 on 2018-08-18 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("program", "0066_speaker_email")]

    operations = [
        migrations.AlterModelOptions(
            name="eventproposal",
            options={
                "permissions": (("can_approve_proposals", "Can approve proposals"),),
            },
        ),
    ]
