# Generated by Django 2.1 on 2018-08-18 17:57
from __future__ import annotations

from django.db import migrations


def add_email(apps, schema_editor):
    Speaker = apps.get_model("program", "Speaker")
    SpeakerProposal = apps.get_model("program", "SpeakerProposal")

    for speaker in Speaker.objects.all():
        if speaker.proposal and not speaker.email:
            speaker.email = speaker.proposal.user.email
            speaker.save()

    for speaker_proposal in SpeakerProposal.objects.all():
        if not speaker_proposal.email:
            speaker_proposal.email = speaker_proposal.user.email
            speaker_proposal.save()


class Migration(migrations.Migration):
    dependencies = [("program", "0067_auto_20180818_1634")]

    operations = [migrations.RunPython(add_email)]
