# Generated by Django 2.0.4 on 2018-08-27 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("program", "0070_auto_20180819_1729")]

    operations = [migrations.AlterModelOptions(name="eventproposal", options={})]
