# Generated by Django 2.2.2 on 2019-06-16 15:46
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0071_auto_20180827_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerproposal",
            name="email",
            field=models.EmailField(
                help_text="The email of the speaker (defaults to the logged in user if empty).",
                max_length=150,
            ),
        ),
    ]
