# Generated by Django 2.2.3 on 2019-07-31 10:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0072_auto_20190616_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="use_provided_speaker_laptop",
            field=models.BooleanField(
                default=False,
                help_text="Will you be using the provided speaker laptop?",
            ),
        ),
    ]
