# Generated by Django 2.2.3 on 2019-08-01 07:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0073_eventproposal_use_provided_speaker_laptop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="use_provided_speaker_laptop",
            field=models.BooleanField(
                default=True,
                help_text="Will you be using the provided speaker laptop?",
            ),
        ),
    ]
