# Generated by Django 3.0.3 on 2020-02-14 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0076_auto_20200214_0143"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventfeedback",
            old_name="feedback",
            new_name="comment",
        ),
    ]
