# Generated by Django 3.0.3 on 2020-02-22 13:59

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0078_auto_20200214_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinstance",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="This field is mostly here to keep Frab happy, it is not the PK of the model",
                null=True,
            ),
        ),
    ]
