# Generated by Django 3.0.3 on 2020-02-22 15:13

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0081_populate_eventinstance_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventinstance",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="This field is mostly here to keep Frab happy, it is not the PK of the model",
                unique=True,
            ),
        ),
    ]
