# Generated by Django 3.0.3 on 2020-02-26 17:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0082_eventinstance_uuid_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="The reason this proposal was accepted or rejected.",
            ),
        ),
        migrations.AddField(
            model_name="speakerproposal",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="The reason this proposal was accepted or rejected.",
            ),
        ),
    ]
