# Generated by Django 3.0.3 on 2020-03-31 22:24

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.expressions
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camps", "0034_add_team_permission_sets"),
        ("program", "0084_auto_20200229_1801"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddField(
            model_name="event",
            name="demand",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The estimated demand for this event. Used by the autoscheduler to pick the optimal location for events. Set to 0 to disable demand constraints for this event.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The duration of this event. Leave this blank to use the default from the eventtype. Note: Leave this blank to support autoscheduling.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventinstance",
            name="autoscheduled",
            field=models.BooleanField(
                default=False,
                help_text="True if this was created by the autoscheduler.",
            ),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="capacity",
            field=models.PositiveIntegerField(
                default=20,
                help_text="The capacity of this location. Used by the autoscheduler.",
            ),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="conflicts",
            field=models.ManyToManyField(
                help_text="Select the locations which this location conflicts with. Nothing can be scheduled in a location if a conflicting location has an EventInstance at the same time. Example: If one room can be split into two, then the big room would conflict with each of the two small rooms (but the small rooms would not conflict with eachother).",
                related_name="_eventlocation_conflicts_+",
                to="program.EventLocation",
            ),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="event_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The duration of an event of this type, in minutes. Leave this empty if events of this type can have different durations. Required for autoscheduling.",
            ),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="support_autoscheduling",
            field=models.BooleanField(
                default=False,
                help_text="Check to enable this EventType in the autoscheduler",
            ),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="event_type",
            field=models.ForeignKey(
                help_text="The type of event",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventproposals",
                to="program.EventType",
            ),
        ),
        migrations.CreateModel(
            name="SpeakerProposalAvailability",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "when",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        db_index=True,
                        help_text="The period when this speaker is available or unavailable. Must be 1 hour!",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        db_index=True,
                        help_text="Is the speaker available or unavailable during this hour? Check for available, uncheck for unavailable.",
                    ),
                ),
                (
                    "speakerproposal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The speaker proposal object this availability belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availabilities",
                        to="program.SpeakerProposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeakerAvailability",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "when",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        db_index=True,
                        help_text="The period when this speaker is available or unavailable. Must be 1 hour!",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        db_index=True,
                        help_text="Is the speaker available or unavailable during this hour? Check for available, uncheck for unavailable.",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        help_text="The speaker object this availability belongs to (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availabilities",
                        to="program.Speaker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "when",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        help_text="A period of time where this type of event can be scheduled. Input format is <i>YYYY-MM-DD HH:MM</i>"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this session (optional)."
                    ),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        help_text="The Camp this EventSession belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventsessions",
                        to="camps.Camp",
                    ),
                ),
                (
                    "event_location",
                    models.ForeignKey(
                        help_text="The event location this session is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventsessions",
                        to="program.EventLocation",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        help_text="The type of event this session is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventsessions",
                        to="program.EventType",
                    ),
                ),
            ],
            options={"ordering": ["when", "event_type", "event_location"],},
        ),
        migrations.AddConstraint(
            model_name="speakerproposalavailability",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (django.db.models.expressions.F("speakerproposal"), "="),
                    ("when", "&&"),
                ],
                name="prevent_speakerproposalavailability_overlaps",
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeravailability",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (django.db.models.expressions.F("speaker"), "="),
                    ("when", "&&"),
                ],
                name="prevent_speakeravailability_overlaps",
            ),
        ),
    ]
