# Generated by Django 3.0.3 on 2020-04-04 00:52

import django.contrib.postgres.constraints
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0085_sessions_and_availability"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventinstance",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("when", "&&"), ("location", "=")],
                name="prevent_eventinstance_location_overlaps",
            ),
        ),
    ]
