# Generated by Django 3.0.3 on 2020-04-21 17:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0088_speaker_event_conflicts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerproposal",
            name="event_conflicts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pick the Events this person wishes to attend, and we will attempt to avoid scheduling conflicts.",
                related_name="speaker_proposal_conflicts",
                to="program.Event",
            ),
        ),
    ]
