# Generated by Django 3.0.3 on 2020-04-21 20:54

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("utils", "0004_uuidtaggeditem"),
        ("program", "0090_event_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventproposal",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="utils.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
