# Generated by Django 3.0.3 on 2020-04-22 06:16

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0091_eventproposal_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="This field is not the PK of the model. It is used to create EventSlot UUID for FRAB and iCal and other calendaring purposes.",
            ),
        ),
    ]
