# Generated by Django 3.0.3 on 2020-05-03 12:36
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0092_event_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="The reason this proposal was accepted or rejected. This text will be included in the email to the submitter. Leave blank to send a standard email.",
            ),
        ),
        migrations.AlterField(
            model_name="speakerproposal",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="The reason this proposal was accepted or rejected. This text will be included in the email to the submitter. Leave blank to send a standard email.",
            ),
        ),
    ]
