# Generated by Django 3.0.3 on 2020-05-03 16:57

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0004_uuidtaggeditem"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("program", "0093_proposal_reason_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="utils.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
