# Generated by Django 3.0.3 on 2020-06-22 08:51

import django.contrib.postgres.constraints
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0094_tags_blank"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventsession",
            name="prevent_event_session_event_type_event_location_overlaps",
        ),
        migrations.AlterField(
            model_name="event",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The duration of this event in minutes. Leave blank to use the default from the event_type.",
            ),
        ),
        migrations.AlterField(
            model_name="eventproposal",
            name="duration",
            field=models.IntegerField(
                blank=True,
                help_text="How much time (in minutes) should we set aside for this event?",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("when", "&&"),
                    ("event_location", "="),
                    ("event_type", "="),
                    ("event_duration_minutes", "="),
                ],
                name="prevent_event_session_event_type_event_location_overlaps",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsession",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("event_location", "="),
                    ("event_type", "="),
                    ("event_duration_minutes", "="),
                    ("when", "-|-"),
                ],
                name="prevent_adjacent_eventsessions",
            ),
        ),
    ]
