# Generated by Django 3.2.5 on 2021-08-15 20:03
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0098_auto_20200811_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="event_conflicts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The Events this person wishes to attend. The AutoScheduler will avoid conflicts.",
                related_name="speaker_conflicts",
                to="program.Event",
            ),
        ),
    ]
