# Generated by Django 3.2.12 on 2022-05-27 17:51
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0099_alter_speaker_event_conflicts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="eventtype",
            name="order",
            field=models.IntegerField(default=0, help_text="Order for showing the event type in a list"),
        ),
    ]
