# Generated by Django 3.2.12 on 2022-05-27 14:15

from django.db import migrations


def remove_video_urls(apps, schema_editor):
    Event = apps.get_model('program', 'Event')
    Url = apps.get_model('program', 'Url')
    UrlType = apps.get_model('program', 'UrlType')
    recording, _ = UrlType.objects.get_or_create(name='Recording')
    for event in Event.objects.exclude(video_url__isnull=True).all():
        Url.objects.get_or_create(url=event.video_url, url_type=recording, event=event)


def revert_video_urls(apps, schema_editor):
    Event = apps.get_model('program', 'Event')
    Url = apps.get_model('program', 'Url')
    UrlType = apps.get_model('program', 'UrlType')
    recording, _ = UrlType.objects.get_or_create(name='Recording')
    for url in Url.objects.filter(url_type=recording, event__isnull=False):
        url.event.video_url = url.url
        url.event.save()
        url.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0099_alter_speaker_event_conflicts'),
    ]

    operations = [
        migrations.RunPython(remove_video_urls, revert_video_urls),
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
    ]
