# Generated by Django 3.2.12 on 2022-07-15 06:51
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0100_auto_20220527_1951"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="video_url",
        ),
    ]
