# Generated by Django 4.2 on 2023-04-03 20:11
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0101_remove_event_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlocation",
            name="conflicts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the locations which this location conflicts with. Nothing can be scheduled in a location if a conflicting location has a scheduled Event at the same time. Example: If one room can be split into two, then the big room would conflict with each of the two small rooms (but the small rooms would not conflict with eachother).",
                to="program.eventlocation",
            ),
        ),
    ]
