# Generated by Django 3.2.14 on 2022-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0101_remove_event_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='recordable',
            field=models.BooleanField(default=True, help_text='Whether or not events of this type are something which can be recorded. This gives "video_recording" on an event of this type meaning. Ie. "Talk" is recordable, "Recreational Event" is not.'),
        ),
    ]
