# Generated by Django 4.2 on 2023-05-18 13:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0102_alter_eventlocation_conflicts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventproposal",
            name="abstract",
            field=models.TextField(
                help_text="The abstract for this event. Describe what the audience can expect to see/hear.",
            ),
        ),
    ]
