# Generated by Django 4.2 on 2023-05-19 16:22
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0036_camp_economy_team"),
        ("program", "0103_alter_eventproposal_abstract"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="speaker",
            unique_together={("camp", "slug")},
        ),
    ]
