# Generated by Django 4.2.20 on 2025-04-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0105_cascade_delete_event_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_streaming',
            field=models.BooleanField(default=True, help_text='Do we intend to stream video of this event?'),
        ),
        migrations.AddField(
            model_name='eventproposal',
            name='allow_video_streaming',
            field=models.BooleanField(default=False, help_text='Uncheck if you do not want the event streamed.'),
        ),
    ]
