# Generated by Django 1.10.5 on 2017-08-19 20:22
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("tickets", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="discountticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.TicketType",
            ),
        ),
        migrations.AlterField(
            model_name="shopticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.TicketType",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.TicketType",
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="camps.Camp",
            ),
        ),
    ]
