# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0022_camp_colour'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseticket',
            name='camp',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camps.Camp'),
        ),
    ]
