# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170817_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Camp'),
        ),
    ]
