# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170817_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopticket',
            name='checked_in',
        ),
        migrations.AddField(
            model_name='baseticket',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
