# Generated by Django 1.10.5 on 2017-08-23 10:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("tickets", "0003_auto_20170819_2309")]

    operations = [
        migrations.AddField(
            model_name="discountticket",
            name="badge_handed_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopticket",
            name="badge_handed_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsorticket",
            name="badge_handed_out",
            field=models.BooleanField(default=False),
        ),
    ]
