# Generated by Django 1.10.5 on 2018-03-18 08:06
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("tickets", "0004_auto_20170823_1228")]

    operations = [
        migrations.AlterField(
            model_name="discountticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.TicketType",
            ),
        ),
        migrations.AlterField(
            model_name="shopticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shoptickets",
                to="shop.Order",
            ),
        ),
        migrations.AlterField(
            model_name="shopticket",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.Product",
            ),
        ),
        migrations.AlterField(
            model_name="shopticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.TicketType",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorticket",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sponsors.Sponsor",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorticket",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.TicketType",
            ),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="camps.Camp",
            ),
        ),
    ]
