# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20170818_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseticket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='discountticket',
            name='created',
        ),
        migrations.RemoveField(
            model_name='discountticket',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='discountticket',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='shopticket',
            name='created',
        ),
        migrations.RemoveField(
            model_name='shopticket',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='shopticket',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='sponsorticket',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sponsorticket',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sponsorticket',
            name='uuid',
        ),
        migrations.AddField(
            model_name='baseticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseticket',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='baseticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountticket',
            name='baseticket_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.BaseTicket'),
        ),
        migrations.AlterField(
            model_name='shopticket',
            name='baseticket_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.BaseTicket'),
        ),
        migrations.AlterField(
            model_name='sponsorticket',
            name='baseticket_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.BaseTicket'),
        ),
    ]
