# Generated by Django 2.2.2 on 2019-07-18 18:52
from __future__ import annotations

from django.conf import settings
from django.db import migrations

from tickets.models import create_ticket_token


def save_tokens(apps, schema_editor):
    ShopTicket = apps.get_model("tickets", "ShopTicket")
    SponsorTicket = apps.get_model("tickets", "SponsorTicket")
    DiscountTicket = apps.get_model("tickets", "DiscountTicket")

    for model in (ShopTicket, SponsorTicket, DiscountTicket):
        for ticket in model.objects.all():
            token = create_ticket_token(
                f"{ticket.uuid}{settings.SECRET_KEY}".encode(),
            )
            ticket.token = token
            ticket.save()


class Migration(migrations.Migration):
    dependencies = [("tickets", "0006_auto_20190616_1746")]

    operations = [migrations.RunPython(save_tokens)]
