# Generated by Django 2.2.3 on 2019-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190718_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='includes_badge',
            field=models.BooleanField(default=False),
        ),
    ]
