# Generated by Django 2.2.3 on 2019-08-03 20:41
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0013_tickettype_single_ticket_per_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountticket",
            name="badge_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="discountticket",
            name="token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="shopticket",
            name="badge_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="shopticket",
            name="token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="sponsorticket",
            name="badge_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="sponsorticket",
            name="token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
