# Generated by Django 3.2.5 on 2021-07-26 19:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0064_add_product_comment_and_cost"),
        ("tickets", "0014_auto_20190803_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopticket",
            name="opr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shoptickets",
                to="shop.orderproductrelation",
            ),
        ),
    ]
