# Generated by Django 3.2.5 on 2021-07-26 19:52
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0064_add_product_comment_and_cost"),
        ("tickets", "0016_populate_opr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopticket",
            name="opr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shoptickets",
                to="shop.orderproductrelation",
            ),
        ),
    ]
