# Generated by Django 3.2.5 on 2021-07-26 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0017_shopticket_opr_not_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopticket",
            name="order",
        ),
    ]
