# Generated by Django 3.2.5 on 2021-08-02 17:56
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0018_remove_shopticket_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountticket",
            name="used_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="shopticket",
            name="used_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="sponsorticket",
            name="used_time",
            field=models.DateTimeField(null=True),
        ),
    ]
