# Generated by Django 3.2.7 on 2021-10-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0035_fix_posreport_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0021_auto_20210803_0521"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountticket",
            name="used_pos",
            field=models.ForeignKey(
                blank=True,
                help_text="The Pos this ticket was scanned in",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="economy.pos",
            ),
        ),
        migrations.AddField(
            model_name="discountticket",
            name="used_pos_username",
            field=models.ForeignKey(
                blank=True,
                help_text="The PoS user who scanned this ticket",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shopticket",
            name="used_pos",
            field=models.ForeignKey(
                blank=True,
                help_text="The Pos this ticket was scanned in",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="economy.pos",
            ),
        ),
        migrations.AddField(
            model_name="shopticket",
            name="used_pos_username",
            field=models.ForeignKey(
                blank=True,
                help_text="The PoS user who scanned this ticket",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sponsorticket",
            name="used_pos",
            field=models.ForeignKey(
                blank=True,
                help_text="The Pos this ticket was scanned in",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="economy.pos",
            ),
        ),
        migrations.AddField(
            model_name="sponsorticket",
            name="used_pos_username",
            field=models.ForeignKey(
                blank=True,
                help_text="The PoS user who scanned this ticket",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
