# Generated by Django 3.2.8 on 2021-10-06 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0022_used_pos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discountticket",
            old_name="used_time",
            new_name="used_at",
        ),
        migrations.RenameField(
            model_name="discountticket",
            old_name="used_pos_username",
            new_name="used_pos_user",
        ),
        migrations.RenameField(
            model_name="shopticket",
            old_name="used_time",
            new_name="used_at",
        ),
        migrations.RenameField(
            model_name="shopticket",
            old_name="used_pos_username",
            new_name="used_pos_user",
        ),
        migrations.RenameField(
            model_name="sponsorticket",
            old_name="used_time",
            new_name="used_at",
        ),
        migrations.RenameField(
            model_name="sponsorticket",
            old_name="used_pos_username",
            new_name="used_pos_user",
        ),
        migrations.RemoveField(
            model_name="discountticket",
            name="used",
        ),
        migrations.RemoveField(
            model_name="shopticket",
            name="used",
        ),
        migrations.RemoveField(
            model_name="sponsorticket",
            name="used",
        ),
    ]
