# Generated by Django 4.2.3 on 2023-07-23 08:49
from __future__ import annotations

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0084_subproductrelation_product_sub_products"),
        ("tickets", "0023_auto_20211006_2310"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopticket",
            name="bundle_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="shop.product",
            ),
        ),
        migrations.CreateModel(
            name="TicketGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "opr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticketgroups",
                        to="shop.orderproductrelation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ticket_group"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="shopticket",
            name="ticket_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="tickets.ticketgroup",
            ),
        ),
    ]
