# Generated by Django 4.2.3 on 2023-07-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0084_subproductrelation_product_sub_products"),
        ("tickets", "0023_auto_20211006_2310"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopticket",
            name="container_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_product_tickets",
                to="shop.product",
            ),
        ),
    ]
