# Generated by Django 4.2.21 on 2025-06-15 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0024_shopticket_bundle_product_ticketgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountticket',
            name='user',
            field=models.ForeignKey(help_text='The user to whom this DiscountTicket belongs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
