# Generated by Django 4.2.21 on 2025-06-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0046_remove_posreport_bank_responsible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0025_discountticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeTicket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('badge_handed_out', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('badge_token', models.CharField(blank=True, max_length=64)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.tickettype')),
                ('used_pos', models.ForeignKey(blank=True, help_text='The Pos this ticket was scanned in', null=True, on_delete=django.db.models.deletion.PROTECT, to='economy.pos')),
                ('used_pos_user', models.ForeignKey(blank=True, help_text='The PoS user who scanned this ticket', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user to whom this PrizeTicket belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='prize_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('prize_ticket'), models.Model),
        ),
        migrations.DeleteModel(
            name='DiscountTicket',
        ),
    ]
