# Generated by Django 4.2.21 on 2025-06-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_prizeticket_delete_discountticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopticket',
            name='email',
        ),
        migrations.AddField(
            model_name='prizeticket',
            name='comment',
            field=models.TextField(blank=True, help_text='A comment about this PrizeTicket (what was it given for)'),
        ),
    ]
