# Generated by Django 4.2.21 on 2025-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0027_remove_shopticket_email_prizeticket_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prizeticket",
            name="comment",
            field=models.TextField(
                help_text="A comment about this PrizeTicket (what was it given for)"
            ),
        ),
    ]
