# Generated by Django 5.2.9 on 2025-12-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_prizeticket_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizeticket',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='shopticket',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sponsorticket',
            options={'ordering': ['-created']},
        ),
    ]
