# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_prizeticket_options_alter_shopticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketgroup',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['-created']},
        ),
    ]
