# Generated by Django 2.1.3 on 2018-11-20 17:35
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("economy", "0003_auto_20180917_1933")]

    operations = [
        migrations.AlterField(
            model_name="reimbursement",
            name="user",
            field=models.ForeignKey(
                help_text="The economy team member who created this reimbursement.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_reimbursements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
