# Generated by Django 2.1.7 on 2019-03-27 08:36
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("economy", "0006_auto_20190120_1642")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="The invoice date for this Expense. This must match the invoice date on the documentation uploaded below. Format is YYYY-MM-DD.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="The invoice date for this Revenue. This must match the invoice date on the documentation uploaded below. Format is YYYY-MM-DD.",
                null=True,
            ),
        ),
    ]
