# Generated by Django 3.1 on 2020-08-13 16:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0013_auto_20200811_1015"),
    ]

    operations = [
        migrations.AddField(
            model_name="posreport",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Any comments about this PosReport",
            ),
        ),
    ]
