# Generated by Django 3.1 on 2020-09-02 20:39
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0015_auto_20200813_2345"),
    ]

    operations = [
        migrations.AddField(
            model_name="posreport",
            name="hax_sold_izettle",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of HAX sold through the iZettle from the POS",
            ),
        ),
    ]
