# Generated by Django 3.1 on 2020-09-02 22:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0016_posreport_hax_sold_izettle"),
    ]

    operations = [
        migrations.AddField(
            model_name="posreport",
            name="hax_sold_website",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of HAX sold through webshop tickets being used in the POS",
            ),
        ),
    ]
