# Generated by Django 3.1 on 2020-09-02 23:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0017_posreport_hax_sold_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="posreport",
            name="dkk_sales_izettle",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The total DKK amount in iZettle cash sales",
            ),
        ),
    ]
