# Generated by Django 3.2.7 on 2021-09-02 10:06
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0018_posreport_dkk_sales_izettle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reimbursement",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Economy Team notes for this reimbursement. Only visible to the Economy team and the reimbursed user.",
            ),
        ),
        migrations.AlterField(
            model_name="reimbursement",
            name="paid",
            field=models.BooleanField(
                default=False,
                help_text="Check when this reimbursement has been paid to the user. Do not check until the bank transfer has been fully approved.",
            ),
        ),
    ]
