# Generated by Django 3.2.7 on 2021-09-02 12:00
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0019_fix_reimbursement_help_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="reimbursement",
            field=models.ForeignKey(
                blank=True,
                help_text="The reimbursement for this expense, if any. This is a dual-purpose field. If expense.paid_by_bornhack is true then expense.reimbursement references the reimbursement which this expense is created to cover. If expense.paid_by_bornhack is false then expense.reimbursement references the reimbursement which reimbursed this expense.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="economy.reimbursement",
            ),
        ),
    ]
