# Generated by Django 3.2.7 on 2021-09-03 11:28

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0020_alter_expense_reimbursement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="The name of the bank", max_length=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the bank account",
                        max_length=100,
                    ),
                ),
                (
                    "reg_no",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_reg_no",
                                message="Reg number must be 4 digits.",
                                regex="^[0-9]{4}$",
                            ),
                        ],
                    ),
                ),
                (
                    "account_no",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_account_no",
                                message="Account number must be 6-12 digits.",
                                regex="^[0-9]{6,12}$",
                            ),
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date we began using this bank account.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The date we stopped using this bank account.",
                        null=True,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        help_text="The bank this bank account belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="economy.bank",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="The date of this transaction.")),
                (
                    "text",
                    models.CharField(
                        help_text="The text for this transaction.",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of this transaction. Negative numbers means money left the bank account, positive numbers mean money was put into the bank account.",
                        max_digits=10,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The balance of the account after this transaction.",
                        max_digits=10,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        help_text="The bank account this transaction belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="economy.bankaccount",
                    ),
                ),
            ],
            options={
                "get_latest_by": "created",
            },
        ),
    ]
