# Generated by Django 3.2.7 on 2021-09-05 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0022_create_coinify_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coinifybalance",
            options={"get_latest_by": ["date"], "ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="coinifyinvoice",
            options={
                "get_latest_by": ["coinify_created"],
                "ordering": ["-coinify_created"],
            },
        ),
        migrations.AlterModelOptions(
            name="coinifypayout",
            options={
                "get_latest_by": ["coinify_created"],
                "ordering": ["-coinify_created"],
            },
        ),
    ]
