# Generated by Django 3.2.7 on 2021-09-13 03:52
from __future__ import annotations

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0026_alter_clearhaussettlement_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZettleBalance",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "statement_time",
                    models.DateTimeField(
                        help_text="The date and time this movement was added to the account statement.",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time this payment was made. Can be empty if this transaction is not a customer payment.",
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.IntegerField(
                        blank=True,
                        help_text="The reference for this payment. Can be empty if this transaction is not a customer payment.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of this transaction.",
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of this transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Our balance in Zettles systems after this transaction.",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_time"],
                "get_latest_by": ["statement_time"],
            },
        ),
        migrations.CreateModel(
            name="ZettleReceipt",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "zettle_created",
                    models.DateTimeField(
                        help_text="The date and time this receipt was created in Zettles end",
                    ),
                ),
                (
                    "receipt_number",
                    models.IntegerField(help_text="The Zettle receipt number."),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The part of the total amount which is VAT",
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total amount the customer paid",
                        max_digits=12,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The payment fee BornHack has to pay to receive this payment",
                        max_digits=12,
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The part of the payment which goes to BornHack after fees have been substracted.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(help_text="The payment method", max_length=100),
                ),
                (
                    "card_issuer",
                    models.CharField(
                        blank=True,
                        help_text="The card issuer. Can be empty if this was not a card payment.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "staff",
                    models.CharField(
                        help_text="The Zettle account which was used to make this sale.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The description of this transaction.",
                        max_length=255,
                    ),
                ),
                ("sold_via", models.CharField(help_text="Always POS?", max_length=100)),
            ],
            options={
                "ordering": ["-zettle_created"],
                "get_latest_by": ["zettle_created"],
            },
        ),
    ]
