# Generated by Django 3.2.7 on 2021-09-25 18:41
from __future__ import annotations

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0028_mobilepaytransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_no",
            field=models.CharField(
                help_text="The Danish account number of the bank account",
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_account_no",
                        message="Account number must be 6-12 digits.",
                        regex="^[0-9]{6,12}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="reg_no",
            field=models.CharField(
                help_text="The Danish reg. number of the bank account",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_reg_no",
                        message="Reg number must be 4 digits.",
                        regex="^[0-9]{4}$",
                    ),
                ],
            ),
        ),
    ]
