# Generated by Django 3.2.7 on 2021-10-03 11:22
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0031_accountingexport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posreport",
            old_name="hax_sold_website",
            new_name="hax_sold_website_old",
        ),
    ]
