# Generated by Django 3.2.7 on 2021-10-03 11:30

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0033_alter_posreport_hax_sold_website_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="posreport",
            name="period",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True,
                help_text="The time period this report covers",
                null=True,
            ),
        ),
    ]
