# Generated by Django 3.2.7 on 2021-10-03 11:30
import datetime

from django.db import migrations


def fix_posreport_periods(apps, schema_editor):
    PosReport = apps.get_model("economy", "PosReport")
    for pr in PosReport.objects.all():
        start = datetime.datetime.combine(pr.date, datetime.time(8, 0))
        pr.period = (start, start + datetime.timedelta(hours=24))
        pr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0034_posreport_period"),
    ]

    operations = [migrations.RunPython(fix_posreport_periods)]
