# Generated by Django 3.2.7 on 2021-10-03 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0035_fix_posreport_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posreport",
            options={"ordering": ["period", "pos"]},
        ),
        migrations.RemoveField(
            model_name="posreport",
            name="date",
        ),
    ]
