# Generated by Django 4.2.3 on 2023-09-24 05:25
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("economy", "0037_alter_pos_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="bank_account",
            field=models.TextField(
                default="",
                help_text="The bank account where you want the payment of this reimbursement transferred to. For transfers outside Denmark please include IBAN and BIC.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reimbursement",
            name="user",
            field=models.ForeignKey(
                help_text="The user who created this reimbursement.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_reimbursements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
