# Generated by Django 4.2.10 on 2024-09-19 10:46
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0039_posproduct_pos_external_id_alter_pos_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posproduct",
            name="expenses",
            field=models.ManyToManyField(
                blank=True,
                help_text="The related expenses for this PosProduct. Only expenses related to a Pos-team are shown. For products composed of multiple ingredients all relevant expenses should be picked.",
                to="economy.expense",
            ),
        ),
    ]
