# Generated by Django 4.2.16 on 2024-09-28 09:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0054_create_team_groups"),
        ("economy", "0040_alter_posproduct_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="responsible_team",
            field=models.ForeignKey(
                help_text="The team to which this Expense belongs. A team lead will need to approve the expense. When in doubt pick the Orga team.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="teams.team",
            ),
        ),
    ]
