# Generated by Django 4.2.16 on 2025-02-16 10:44
from __future__ import annotations

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0087_coinifyapipaymentintent"),
        ("economy", "0041_alter_expense_responsible_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinifyPaymentIntent",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("coinify_id", models.UUIDField(help_text="Coinifys internal ID for this invoice")),
                ("coinify_created", models.DateTimeField(help_text="Created datetime in Coinifys end")),
                ("reference_type", models.CharField(help_text="Coinifys reference type", max_length=100)),
                ("merchant_id", models.UUIDField(help_text="The Merchant ID in Coinify's system.")),
                ("merchant_name", models.TextField(help_text="The Merchant name as set in Coinify's system.")),
                (
                    "subaccount_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier of a created sub-account.",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "subaccount_name",
                    models.TextField(blank=True, help_text="Name given when creating the sub-account.", null=True),
                ),
                ("state", models.CharField(help_text="Coinify intent state", max_length=100)),
                ("state_reason", models.CharField(help_text="Coinify intent state reason", max_length=100)),
                ("original_order_id", models.CharField(blank=True, help_text="Order id", max_length=100, null=True)),
                ("customer_email", models.TextField()),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, help_text="The requested amount", max_digits=12),
                ),
                ("requested_currency", models.CharField(help_text="The requested currency.", max_length=3)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="The payment amount", max_digits=12, null=True),
                ),
                ("currency", models.CharField(blank=True, help_text="The payment currency.", max_length=3, null=True)),
                (
                    "api_payment_intent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The original api payment intent",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="economy_coinify_payment_intents",
                        to="shop.coinifyapipaymentintent",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Order this payment intent is for",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="economy_coinify_payment_intents",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-coinify_created"],
                "get_latest_by": ["coinify_created"],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin("coinify_payment_intent"), models.Model),
        ),
    ]
