# Generated by Django 4.2.16 on 2025-02-16 13:01
from __future__ import annotations

import uuid

import django_prometheus.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0042_coinifypaymentintent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinifySettlement",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "settlement_id",
                    models.CharField(help_text="The internal coinify id for the settlement", max_length=36),
                ),
                ("account", models.CharField(help_text="The settlement account", max_length=100)),
                ("gross_amount", models.DecimalField(decimal_places=2, help_text="The gross amount", max_digits=12)),
                ("fee", models.DecimalField(decimal_places=2, help_text="The payout fee", max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, help_text="The net amount", max_digits=12)),
                ("payout_amount", models.DecimalField(decimal_places=2, help_text="The payout amount", max_digits=12)),
                ("create_time", models.DateTimeField(help_text="Created datetime in Coinifys end for this payout")),
            ],
            options={
                "abstract": False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin("coinify_settlement"), models.Model),
        ),
    ]
