# Generated by Django 4.2.21 on 2025-06-09 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0043_coinifysettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='posreport',
            name='bank_responsible_end',
            field=models.ForeignKey(blank=True, help_text='The banker responsible for the day end count of this PosReport', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_report_banker_end', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posreport',
            name='bank_responsible_start',
            field=models.ForeignKey(blank=True, help_text='The banker responsible for the day start count of this PosReport', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_report_banker_start', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posreport',
            name='pos_responsible_end',
            field=models.ForeignKey(blank=True, help_text='The pos responsible for the day end count of this PosReport', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_report_pos_end', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posreport',
            name='pos_responsible_start',
            field=models.ForeignKey(blank=True, help_text='The pos responsible for the day start count of this PosReport', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_report_pos_start', to=settings.AUTH_USER_MODEL),
        ),
    ]
