# Generated by Django 4.2.21 on 2025-06-09 18:13
from __future__ import annotations

from django.db import migrations


def populate_pos_people(apps, schema_editor) -> None:
    PosReport = apps.get_model("economy", "PosReport")
    for pr in PosReport.objects.all():
        pr.bank_responsible_start = pr.bank_responsible
        pr.bank_responsible_end = pr.bank_responsible
        pr.pos_responsible_start = pr.pos_responsible
        pr.pos_responsible_end = pr.pos_responsible
        pr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0044_posreport_bank_responsible_end_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_pos_people),
    ]
