# Generated by Django 4.2.21 on 2025-06-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0045_populate_bank_and_pos_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posreport',
            name='bank_responsible',
        ),
        migrations.RemoveField(
            model_name='posreport',
            name='pos_responsible',
        ),
    ]
