# Generated by Django 4.2.21 on 2025-12-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0046_remove_posreport_bank_responsible_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="responsible_team",
        ),
        migrations.RemoveField(
            model_name="revenue",
            name="invoice_fk",
        ),
        migrations.RemoveField(
            model_name="revenue",
            name="responsible_team",
        ),
        migrations.AddField(
            model_name="expense",
            name="created_for_reimbursement",
            field=models.BooleanField(
                default=False, help_text="True if this expense was created to pay back a reimbursement"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("", "Unknown"),
                    (
                        "Paid by BornHack",
                        (
                            ("PAID_WITH_TYKLINGS_MASTERCARD", "Expense was paid with Tyklings BornHack Mastercard"),
                            ("PAID_WITH_AHFS_MASTERCARD", "Expense was paid with ahfs BornHack Mastercard"),
                            ("PAID_WITH_VIDIRS_MASTERCARD", "Expense was paid with Vidirs BornHack Mastercard"),
                            ("PAID_IN_NETBANK", "Expense was paid with bank transfer from BornHacks netbank"),
                            ("PAID_WITH_BORNHACKS_CASH", "Expense was paid with BornHacks cash"),
                            ("PAID_LEGACY", "Expense was paid by BornHack before we started tracking payment status"),
                        ),
                    ),
                    (
                        "Paid by Participant",
                        (
                            ("PAID_NEEDS_REIMBURSEMENT", "Expense was paid by me, I need a reimbursement"),
                            ("PAID_AND_REIMBURSED", "Expense has been reimbursed to the volunteer"),
                        ),
                    ),
                    ("Unpaid", (("UNPAID_NEEDS_PAYMENT", "Expense is unpaid"),)),
                ],
                help_text="Payment status for this expense.",
                default="",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="created_for_reimbursement",
            field=models.BooleanField(
                default=False, help_text="True if this revenue was created to settle a reimbursement"
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("", "Unknown"),
                    (
                        "Paid to BornHack",
                        (
                            ("PAID_TO_TYKLINGS_MASTERCARD", "Revenue was credited to Tyklings BornHack Mastercard"),
                            ("PAID_TO_AHFS_MASTERCARD", "Revenue was credited to ahfs BornHack Mastercard"),
                            ("PAID_TO_VIDIRS_MASTERCARD", "Revenue was credited to Vidirs BornHack Mastercard"),
                            ("PAID_IN_NETBANK", "Revenue was transferred to a BornHack bank account"),
                            ("PAID_IN_CASH", "Revenue was paid to BornHack with cash"),
                            ("PAID_LEGACY", "Revenue was paid to BornHack before we started tracking payment status"),
                        ),
                    ),
                    (
                        "Paid to Participant",
                        (
                            (
                                "PAID_NEEDS_REDISBURSEMENT",
                                "Revenue has been paid out to me, a redisbursement is needed",
                            ),
                            ("PAID_AND_REDISBURSED", "Revenue has been received from the volunteer"),
                        ),
                    ),
                    ("Unpaid", (("UNPAID_NEEDS_PAYMENT", "Revenue is unpaid"),)),
                ],
                help_text="Payment status for this revenue.",
                default="",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="reimbursement",
            field=models.ForeignKey(
                blank=True,
                help_text="The reimbursement for this revenue, if any. This is a dual-purpose field. If revenue.created_for_reimbursement is True then revenue.reimbursement references the reimbursement which this revenue was created to handle. If revenue.created_for_reimbursement is False then revenue.reimbursement references the reimbursement which redisbursed this revenue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenues",
                to="economy.reimbursement",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="reimbursement",
            field=models.ForeignKey(
                blank=True,
                help_text="The reimbursement for this expense, if any. This is a dual-purpose field. If expense.created_for_reimbursement is True then expense.reimbursement references the reimbursement which this expense was created to handle. If expense.created_for_reimbursement is False then expense.reimbursement references the reimbursement which reimbursed this expense.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="economy.reimbursement",
            ),
        ),
        migrations.AlterField(
            model_name="reimbursement",
            name="bank_account",
            field=models.TextField(
                blank=True,
                help_text="The bank account where you want the payment of this reimbursement transferred to. For transfers outside Denmark please include IBAN and BIC. Bank account is only needed if the reimbursement amout is > 0 DKK (meaning BornHack owes you money).",
                null=True,
            ),
        ),
    ]
