# Generated by Django 4.2.21 on 2025-12-17 20:05

from django.db import migrations

def migrate_expenses(apps, schema_editor) -> None:
    Expense = apps.get_model("economy", "Expense")
    # unreimbursed participant-paid expenses
    Expense.objects.filter(paid_by_bornhack=False, reimbursement__isnull=True).update(
        payment_status="PAID_NEEDS_REIMBURSEMENT"
    )
    # reimbursed participant-paid expenses
    Expense.objects.filter(paid_by_bornhack=False, reimbursement__isnull=False).update(
        payment_status="PAID_AND_REIMBURSED"
    )
    # regular expenses
    Expense.objects.filter(paid_by_bornhack=True, reimbursement__isnull=True).update(payment_status="PAID_LEGACY")
    # reimbursement expenses
    Expense.objects.filter(paid_by_bornhack=True, reimbursement__isnull=False).update(
        payment_status="PAID_IN_NETBANK", created_for_reimbursement=True
    )


def migrate_revenues(apps, schema_editor) -> None:
    Revenue = apps.get_model("economy", "Revenue")
    # update all revenues
    Revenue.objects.all().update(payment_status="PAID_LEGACY")



class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0047_remove_expense_responsible_team_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_expenses),
        migrations.RunPython(migrate_revenues),
    ]
