# Generated by Django 4.2.21 on 2025-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0048_migrate_exp_rev_reimb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='paid',
            field=models.BooleanField(default=False, help_text='Check when this reimbursement has been paid to/from the user. Do not check until the bank transfer has been received/fully approved'),
        ),
    ]
