# Generated by Django 5.2.9 on 2025-12-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0049_alter_reimbursement_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingexport',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='coinifysettlement',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='mobilepaytransaction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='posproductcost',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='possale',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='postransaction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-created']},
        ),
    ]
