# Generated by Django 5.2.14 on 2026-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0051_possale_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='external_id',
            field=models.CharField(help_text='The external ID of the product.', max_length=100, unique=True),
        ),
    ]
