# Generated by Django 5.2.14 on 2026-09-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0052_alter_possale_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='pos_report',
            field=models.ForeignKey(blank=True, help_text='The PosReport to which this PosTransaction belongs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='economy.posreport'),
        ),
        migrations.AlterField(
            model_name='posproduct',
            name='expenses',
            field=models.ManyToManyField(blank=True, help_text='The related expenses for this PosProduct. For products composed of multiple ingredients all relevant expenses should be picked.', to='economy.expense'),
        ),
        migrations.AlterField(
            model_name='posproductcost',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, help_text='The cost/expense (in DKK, including VAT) for each product sold. For products composed of multiple ingredients this number should include the total cost per product sold.', max_digits=8),
        ),
    ]
