# Generated by Django 5.2.14 on 2026-09-14 06:24

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0053_postransaction_pos_report_alter_posproduct_expenses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='posreport',
            name='period',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='The time period this report covers'),
        ),
        migrations.AddConstraint(
            model_name='posreport',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('period', '&&'), ('pos', '=')], name='prevent_pos_report_period_overlaps_for_pos'),
        ),
    ]
