---
name: "IRC Notification on push"
on:
  - "push"

jobs:
  notification:
    runs-on: "ubuntu-latest"
    name: "IRC Notifications"
    steps:
    - name: "IRC notification"
      if: ${{ (github.repository == 'bornhack/bornhack-website') && (github.actor != 'dependabot[bot]') }}
      uses: "Gottox/irc-message-action@v2"
      with:
        server: "irc.baconsvin.org"
        channel: "#bornhack-website"
        nickname: "webteambot"
        message: |-
          ${{ github.actor }} pushed new commits: ${{ github.event.compare }} - latest commit msg: "${{ github.event.head_commit.message }}"
...
