---
name: "Run pre-commit"

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - "main"

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"  # v.4.2.2
      - uses: "actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065"  # v5.6.0
        with:
          python-version: "3.12"
      - uses: "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020"  # v4.4.0
        with:
          node-version: 22
      - uses: "pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd"  # v3.0.1
...

