# Generated by Django 3.0.3 on 2020-03-10 18:02
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dectregistration",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of this registration, like a name/handle, or a location or service name.",
            ),
        ),
        migrations.AlterField(
            model_name="dectregistration",
            name="letters",
            field=models.CharField(
                blank=True,
                help_text="The letters or numbers chosen to represent this DECT number in the phonebook. Optional.",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="dectregistration",
            name="number",
            field=models.CharField(
                help_text="The DECT phonenumber, four digits or more.",
                max_length=9,
            ),
        ),
    ]
