# Generated by Django 3.0.3 on 2020-03-10 18:23
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook", "0002_auto_20200310_1902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dectregistration",
            name="letters",
            field=models.CharField(
                blank=True,
                help_text="The letters or numbers chosen to represent this DECT number in the phonebook. Optional if you specify a number.",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="dectregistration",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="The DECT phonenumber, four digits or more. Optional if you specify letters.",
                max_length=9,
            ),
        ),
    ]
