# Generated by Django 4.2.20 on 2025-04-20 07:23

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("phonebook", "0003_auto_20200310_1923"),
    ]

    operations = [
        migrations.AddField(
            model_name="dectregistration",
            name="ipei",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                help_text="DECT phone IPEI (EMC+PSN)",
                null=True,
                size=2,
            ),
        ),
    ]
