# Generated by Django 4.2.20 on 2025-04-21 12:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_dectregistration_ipei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dectregistration',
            name='ipei',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='DECT phone IPEI (03562,0900847)', null=True, size=2),
        ),
    ]
